-- MyCinematicQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyCinematicQuest: Init phase started.")
    Quest:AddQuestRegion("MyCinematicQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("MyCinematicQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyCinematicQuest", false, false)
    Quest:SetQuestCardObjective("MyCinematicQuest", "Speak with the mysterious stranger", "Oakvale", "")
    Quest:SetQuestGoldReward("MyCinematicQuest", 1000)
    Quest:SetQuestRenownReward("MyCinematicQuest", 100)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyCinematicQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("MysteriousStranger", "MyCinematicQuest/Entities/MysteriousStranger")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("MyCinematicQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_MysteriousStranger = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_MysteriousStranger = nil
    if marker_MysteriousStranger ~= nil and marker_MysteriousStranger.GetPos ~= nil then
        local ok, result = pcall(function() return marker_MysteriousStranger:GetPos() end)
        if ok then
            pos_MysteriousStranger = result
        end
    end
    if pos_MysteriousStranger == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_MysteriousStranger = result
            end
        end
    end
    if pos_MysteriousStranger ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_MysteriousStranger, "MysteriousStranger") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for MysteriousStranger")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local MysteriousStranger = Quest:GetThingWithScriptName("MysteriousStranger")
    if MysteriousStranger ~= nil then
        Quest:SetThingHasInformation(MysteriousStranger, true)
        Quest:MiniMapAddMarker(MysteriousStranger, "MysteriousStranger")
    end

    Quest:Log("MyCinematicQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyCinematicQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyCinematicQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyCinematicQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local MysteriousStranger = Quest:GetThingWithScriptName("MysteriousStranger")
            if MysteriousStranger ~= nil and not MysteriousStranger:IsNull() then
                Quest:ClearThingHasInformation(MysteriousStranger)
                Quest:MiniMapRemoveMarker(MysteriousStranger)
            end

            -- Give rewards
            Quest:GiveHeroGold(1000)
            Quest:GiveHeroExperience(200)
            Quest:GiveHeroRenownPoints(100)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyCinematicQuest", true, false, false)
            Quest:DeactivateQuestLater("MyCinematicQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

