-- EscortNPC.lua
-- Entity script for MyEscortQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("EscortNPC: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("EscortNPC: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            Quest:SetStateBool("escortStarted", true)
            Me:FollowThing(hero, 3.0, true)
            Quest:Pause(5.0)
            local followTarget = "Hero"
            local followThing = nil
            if followTarget == "Hero" then
                followThing = Quest:GetHero()
            else
                followThing = Quest:GetThingWithScriptName(followTarget)
            end
            if followThing ~= nil then
                Me:StopFollowingThing(followThing)
            end
            Quest:SetStateBool("QuestCompleted", true)
            break
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
