-- MyPilgrimageQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyPilgrimageQuest: Init phase started.")
    Quest:AddQuestRegion("MyPilgrimageQuest", "Oakvale")
    Quest:AddQuestRegion("MyPilgrimageQuest", "BarrowFields")
    Quest:AddQuestRegion("MyPilgrimageQuest", "LookoutPoint")
    Quest:AddQuestRegion("MyPilgrimageQuest", "HeroesGuild")
    Quest:SetQuestWorldMapOffset("MyPilgrimageQuest", 300, 320)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyPilgrimageQuest", false, false)
    Quest:SetQuestCardObjective("MyPilgrimageQuest", "Visit Barrow Fields and Lookout Point, then report to the Heroes Guild.", "Oakvale", "HeroesGuild")
    Quest:SetQuestGoldReward("MyPilgrimageQuest", 1800)
    Quest:SetQuestRenownReward("MyPilgrimageQuest", 180)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateBool("Visited Barrow Fields", false)
    Quest:SetStateBool("Visited Lookout Point", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyPilgrimageQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("PilgrimageBarrow", "MyPilgrimageQuest/Entities/PilgrimageBarrow")
    Quest:AddEntityBinding("PilgrimageLookout", "MyPilgrimageQuest/Entities/PilgrimageLookout")
    Quest:AddEntityBinding("PilgrimageGuildMaster", "MyPilgrimageQuest/Entities/PilgrimageGuildMaster")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferBool(context, "Visited Barrow Fields")
    Quest:PersistTransferBool(context, "Visited Lookout Point")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("MyPilgrimageQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_PilgrimageBarrow = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_PilgrimageBarrow = nil
    if marker_PilgrimageBarrow ~= nil and marker_PilgrimageBarrow.GetPos ~= nil then
        local ok, result = pcall(function() return marker_PilgrimageBarrow:GetPos() end)
        if ok then
            pos_PilgrimageBarrow = result
        end
    end
    if pos_PilgrimageBarrow == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_PilgrimageBarrow = result
            end
        end
    end
    if pos_PilgrimageBarrow ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_PilgrimageBarrow, "PilgrimageBarrow") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for PilgrimageBarrow")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_PilgrimageLookout = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_PilgrimageLookout = nil
    if marker_PilgrimageLookout ~= nil and marker_PilgrimageLookout.GetPos ~= nil then
        local ok, result = pcall(function() return marker_PilgrimageLookout:GetPos() end)
        if ok then
            pos_PilgrimageLookout = result
        end
    end
    if pos_PilgrimageLookout == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_PilgrimageLookout = result
            end
        end
    end
    if pos_PilgrimageLookout ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_PilgrimageLookout, "PilgrimageLookout") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for PilgrimageLookout")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_PilgrimageGuildMaster = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_PilgrimageGuildMaster = nil
    if marker_PilgrimageGuildMaster ~= nil and marker_PilgrimageGuildMaster.GetPos ~= nil then
        local ok, result = pcall(function() return marker_PilgrimageGuildMaster:GetPos() end)
        if ok then
            pos_PilgrimageGuildMaster = result
        end
    end
    if pos_PilgrimageGuildMaster == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_PilgrimageGuildMaster = result
            end
        end
    end
    if pos_PilgrimageGuildMaster ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_PilgrimageGuildMaster, "PilgrimageGuildMaster") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for PilgrimageGuildMaster")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local PilgrimageBarrow = Quest:GetThingWithScriptName("PilgrimageBarrow")
    if PilgrimageBarrow ~= nil then
        Quest:SetThingHasInformation(PilgrimageBarrow, true)
        Quest:MiniMapAddMarker(PilgrimageBarrow, "PilgrimageBarrow")
    end
    local PilgrimageLookout = Quest:GetThingWithScriptName("PilgrimageLookout")
    if PilgrimageLookout ~= nil then
        Quest:SetThingHasInformation(PilgrimageLookout, true)
        Quest:MiniMapAddMarker(PilgrimageLookout, "PilgrimageLookout")
    end
    local PilgrimageGuildMaster = Quest:GetThingWithScriptName("PilgrimageGuildMaster")
    if PilgrimageGuildMaster ~= nil then
        Quest:SetThingHasInformation(PilgrimageGuildMaster, true)
        Quest:MiniMapAddMarker(PilgrimageGuildMaster, "PilgrimageGuildMaster")
    end

    Quest:Log("MyPilgrimageQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyPilgrimageQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyPilgrimageQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyPilgrimageQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local PilgrimageBarrow = Quest:GetThingWithScriptName("PilgrimageBarrow")
            if PilgrimageBarrow ~= nil and not PilgrimageBarrow:IsNull() then
                Quest:ClearThingHasInformation(PilgrimageBarrow)
                Quest:MiniMapRemoveMarker(PilgrimageBarrow)
            end
            local PilgrimageLookout = Quest:GetThingWithScriptName("PilgrimageLookout")
            if PilgrimageLookout ~= nil and not PilgrimageLookout:IsNull() then
                Quest:ClearThingHasInformation(PilgrimageLookout)
                Quest:MiniMapRemoveMarker(PilgrimageLookout)
            end
            local PilgrimageGuildMaster = Quest:GetThingWithScriptName("PilgrimageGuildMaster")
            if PilgrimageGuildMaster ~= nil and not PilgrimageGuildMaster:IsNull() then
                Quest:ClearThingHasInformation(PilgrimageGuildMaster)
                Quest:MiniMapRemoveMarker(PilgrimageGuildMaster)
            end

            -- Give rewards
            Quest:GiveHeroGold(1800)
            Quest:GiveHeroExperience(320)
            Quest:GiveHeroRenownPoints(180)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyPilgrimageQuest", true, false, false)
            Quest:DeactivateQuestLater("MyPilgrimageQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

