-- QuestGiver.lua
-- Entity script for MyBoardQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("QuestGiver: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("QuestGiver: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            answer = Quest:GiveHeroYesNoQuestion("A thief is loose in town. Will you stop them?", "Yes", "No", "Not sure")
            Quest:EndMovieSequence()
            if answer ~= nil then
    if answer == 0 then
                Quest:SetStateBool("questAccepted", true)
                Me:SpeakAndWait("Great. The thief was last seen near the market.")
    elseif answer == 1 then
                Me:SpeakAndWait("Perhaps another hero will help.")
    else
                Quest:SetStateBool("questAccepted", true)
                Me:SpeakAndWait("Great. The thief was last seen near the market.")
    end
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
