-- Thief.lua
-- Entity script for MyBoardQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Thief: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Thief: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsKilledByHero() then
            if Quest:GetStateBool("questAccepted") == true then
                Quest:SetStateBool("QuestCompleted", true)
                break
            else
                Me:SpeakAndWait("The thief is dead, but you never accepted the job.")
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
