-- MyDemonDoorQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyDemonDoorQuest: Init phase started.")
    Quest:AddQuestRegion("MyDemonDoorQuest", "Greatwood")
    Quest:SetQuestWorldMapOffset("MyDemonDoorQuest", 250, 380)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyDemonDoorQuest", false, false)
    Quest:SetQuestCardObjective("MyDemonDoorQuest", "Appease the Demon Door", "Greatwood", "")
    Quest:SetQuestGoldReward("MyDemonDoorQuest", 800)
    Quest:SetQuestRenownReward("MyDemonDoorQuest", 80)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyDemonDoorQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("DemonDoor", "MyDemonDoorQuest/Entities/DemonDoor")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Greatwood"})
    Quest:CreateThread("EntitySpawner", {region="Greatwood"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Greatwood"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Greatwood - FSE auto-waits for region load
    Quest:Log("MyDemonDoorQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_DemonDoor = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_DemonDoor = nil
    if marker_DemonDoor ~= nil and marker_DemonDoor.GetPos ~= nil then
        local ok, result = pcall(function() return marker_DemonDoor:GetPos() end)
        if ok then
            pos_DemonDoor = result
        end
    end
    if pos_DemonDoor == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_DemonDoor = result
            end
        end
    end
    if pos_DemonDoor ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_DemonDoor, "DemonDoor") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for DemonDoor")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local DemonDoor = Quest:GetThingWithScriptName("DemonDoor")
    if DemonDoor ~= nil then
        Quest:SetThingHasInformation(DemonDoor, true)
        Quest:MiniMapAddMarker(DemonDoor, "DemonDoor")
    end

    Quest:Log("MyDemonDoorQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyDemonDoorQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyDemonDoorQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyDemonDoorQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local DemonDoor = Quest:GetThingWithScriptName("DemonDoor")
            if DemonDoor ~= nil and not DemonDoor:IsNull() then
                Quest:ClearThingHasInformation(DemonDoor)
                Quest:MiniMapRemoveMarker(DemonDoor)
            end

            -- Give rewards
            Quest:GiveHeroGold(800)
            Quest:GiveHeroExperience(150)
            Quest:GiveHeroRenownPoints(80)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyDemonDoorQuest", true, false, false)
            Quest:DeactivateQuestLater("MyDemonDoorQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

