-- MyTalkQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyTalkQuest: Init phase started.")
    Quest:AddQuestRegion("MyTalkQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("MyTalkQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyTalkQuest", false, false)
    Quest:SetQuestCardObjective("MyTalkQuest", "Talk to the villager", "Oakvale", "")
    Quest:SetQuestGoldReward("MyTalkQuest", 500)
    Quest:SetQuestRenownReward("MyTalkQuest", 50)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyTalkQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("TalkNPC", "MyTalkQuest/Entities/TalkNPC")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("MyTalkQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_TalkNPC = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_TalkNPC = nil
    if marker_TalkNPC ~= nil and marker_TalkNPC.GetPos ~= nil then
        local ok, result = pcall(function() return marker_TalkNPC:GetPos() end)
        if ok then
            pos_TalkNPC = result
        end
    end
    if pos_TalkNPC == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_TalkNPC = result
            end
        end
    end
    if pos_TalkNPC ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_TalkNPC, "TalkNPC") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for TalkNPC")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local TalkNPC = Quest:GetThingWithScriptName("TalkNPC")
    if TalkNPC ~= nil then
        Quest:SetThingHasInformation(TalkNPC, true)
        Quest:MiniMapAddMarker(TalkNPC, "TalkNPC")
    end

    Quest:Log("MyTalkQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyTalkQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyTalkQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyTalkQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local TalkNPC = Quest:GetThingWithScriptName("TalkNPC")
            if TalkNPC ~= nil and not TalkNPC:IsNull() then
                Quest:ClearThingHasInformation(TalkNPC)
                Quest:MiniMapRemoveMarker(TalkNPC)
            end

            -- Give rewards
            Quest:GiveHeroGold(500)
            Quest:GiveHeroExperience(100)
            Quest:GiveHeroRenownPoints(50)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyTalkQuest", true, false, false)
            Quest:DeactivateQuestLater("MyTalkQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

