-- Investigator.lua
-- Entity script for MyInvestigationQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Investigator: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Investigator: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            if Quest:GetStateBool("witness1Talked") == true then
                if Quest:GetStateBool("witness2Talked") == true then
                    Quest:SetStateBool("QuestCompleted", true)
                    break
                else
                    Me:SpeakAndWait("Keep looking. We need both witness statements.")
                end
            else
                Me:SpeakAndWait("Keep looking. We need both witness statements.")
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
