-- Witness2.lua
-- Entity script for MyInvestigationQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Witness2: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Witness2: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            answer = Quest:GiveHeroYesNoQuestion("Will you tell me what you saw?", "Yes, I'll help", "No, leave me alone", "I'm not sure...")
            Quest:EndMovieSequence()
            if answer ~= nil then
    if answer == 0 then
                Me:SpeakAndWait("I saw a hooded figure near the museum last night. Very suspicious!")
                Quest:SetStateBool("witness2Talked", true)
    elseif answer == 1 then
                Me:SpeakAndWait("Fine, fine! I saw someone suspicious near the museum. Happy now?")
                Quest:SetStateBool("witness2Talked", true)
    else
                Me:SpeakAndWait("Fine, fine! I saw someone suspicious near the museum. Happy now?")
                Quest:SetStateBool("witness2Talked", true)
    end
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
