-- TalkNPC.lua
-- Entity script for MyTalkQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("TalkNPC: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("TalkNPC: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            Me:SpeakAndWait("Hello there, hero! I've been waiting for you.")
            Me:SpeakAndWait("Thank you for coming. Your help means a lot to me.")
            Quest:SetStateBool("QuestCompleted", true)
            break
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
