-- NewQuest.lua
-- Generated by FSE Quest Creator Pro
-- Sample quest to test code generation patterns
--
-- NOTE: This quest uses the "Oakvale" region. To determine the actual region
-- name at runtime, use Quest:GetRegionName() and check the FSE log.

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("NewQuest: Init phase started.")

    -- Log the current region name for debugging
    local currentRegion = Quest:GetRegionName()
    Quest:Log("NewQuest: Current region is: " .. (currentRegion or "nil"))

    -- Register the quest region (use region name matching what game loads)
    Quest:AddQuestRegion("NewQuest", "Oakvale")
    Quest:SetStateBool("QuestCompleted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("NewQuest Main() started. Setting up immediately...")

    -- Do immediate setup - no region wait in Main()
    Quest:AddEntityBinding("Karen", "NewQuest/Entities/Karen")
    Quest:FinalizeEntityBindings()
    Quest:Log("NewQuest: Entity bindings finalized")

    -- Quest card setup - using same pattern as MyFirstQuest
    Quest:AddQuestCard("OBJECT_QUEST_CARD_WASP_MENACE", "NewQuest", false, false)
    Quest:SetQuestCardObjective("NewQuest", "MeowMeow", "Oakvale", "")
    Quest:SetQuestGoldReward("NewQuest", 500)
    Quest:SetQuestRenownReward("NewQuest", 500)

    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_WASP_MENACE", "NewQuest", true)
    Quest:Log("NewQuest: Quest card configured")

    -- Show quest start screen
    Quest:KickOffQuestStartScreen("NewQuest", true, true)
    Quest:Log("NewQuest: Start screen kicked off")

    -- Create threads (region-bound threads automatically wait for region)
    -- FSE automatically delays thread execution until the region loads
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
    Quest:Log("NewQuest: Threads created")

    Quest:Log("NewQuest: Main() completed")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound - FSE auto-delays until Oakvale is loaded
    Quest:Log("NewQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_Karen = Quest:GetThingWithScriptName("MK_OVID_DAD")
    if marker_Karen ~= nil then
        local pos_Karen = marker_Karen:GetPos()
        Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_Karen, "Karen")
        Quest:Log("NewQuest: Karen spawned at marker MK_OVID_DAD")
    else
        Quest:Log("NewQuest: WARNING - Marker MK_OVID_DAD not found, spawning at hero")
        local hero = Quest:GetHero()
        local heroPos = hero:GetPos()
        Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", heroPos, "Karen")
    end

    -- Set up quest target highlighting and minimap markers
    local Karen = Quest:GetThingWithScriptName("Karen")
    if Karen ~= nil then
        Quest:SetThingHasInformation(Karen, true)
        Quest:MiniMapAddMarker(Karen, "Karen")
        Quest:Log("NewQuest: Quest target and minimap marker set")
    end

    Quest:Log("NewQuest: EntitySpawner completed.")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            CompleteQuest()
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

function CompleteQuest()
    Quest:Log("NewQuest: CompleteQuest called.")

    -- Clear quest target highlighting and minimap markers
    local Karen = Quest:GetThingWithScriptName("Karen")
    if Karen ~= nil then
        Quest:ClearThingHasInformation(Karen)
        Quest:MiniMapRemoveMarker(Karen)
    end

    -- Give rewards
    Quest:GiveHeroGold(500)
    Quest:GiveHeroExperience(500)
    Quest:GiveHeroRenownPoints(500)
    Quest:GiveHeroMorality(500)
    Quest:GiveHeroObject("OBJECT_SWORD_OF_AEONS", 1)

    -- Complete and deactivate quest
    Quest:SetQuestAsCompleted("NewQuest", false, false, false)
    Quest:DeactivateQuestLater("NewQuest", 1.0)
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end
