-- PilgrimageGuildMaster.lua
-- Entity script for MyPilgrimageQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("PilgrimageGuildMaster: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("PilgrimageGuildMaster: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            if Quest:GetStateBool("visitedBarrowFields") == true then
                if Quest:GetStateBool("visitedLookoutPoint") == true then
                    Me:SpeakAndWait("Well done. Your pilgrimage is complete.")
                    Quest:SetStateBool("QuestCompleted", true)
                    break
                else
                    Me:SpeakAndWait("You still have waypoints to visit before the Guild can certify you.")
                end
            else
                Me:SpeakAndWait("You still have waypoints to visit before the Guild can certify you.")
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
