-- MysteriousStranger.lua
-- Entity script for MyCinematicQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("MysteriousStranger: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("MysteriousStranger: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            Quest:AddScreenTitleMessage("A Mysterious Stranger", 3.0, true)
            Me:SpeakAndWait("Ah... you've finally arrived. I've been expecting you.")
            Quest:Pause(0.5)
            Me:SpeakAndWait("There are forces at work here... forces you cannot yet comprehend.")
            Quest:Pause(0.5)
            Me:SpeakAndWait("But in time, hero, you will understand. In time...")
            Quest:SetStateBool("QuestCompleted", true)
            break
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
