-- VarIntNPC.lua
-- Entity script for VarIntQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("VarIntNPC: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("VarIntNPC: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            var_Count = 3
                Me:SpeakAndWait("Count set to $Count.")
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
