-- VarExternalFlowQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("VarExternalFlowQuest: Init phase started.")
    Quest:SetStateInt("FQT_ActionCounter", 0)
    Quest:SetStateInt("FQT_ActionProcessed", 0)
    Quest:SetStateBool("FQT_StopActions", false)

    Quest:AddQuestRegion("VarExternalFlowQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("VarExternalFlowQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "VarExternalFlowQuest", false, false)
    Quest:SetQuestCardObjective("VarExternalFlowQuest", "Give the item, then talk to the listener", "Oakvale", "")

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("VarExternalFlowQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("VarSource", "VarExternalFlowQuest/Entities/VarSource")
    Quest:AddEntityBinding("VarListener", "VarExternalFlowQuest/Entities/VarListener")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
    Quest:CreateThread("ProcessQuestActions", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("VarExternalFlowQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_VarSource = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_VarSource = nil
    if marker_VarSource ~= nil and marker_VarSource.GetPos ~= nil then
        local ok, result = pcall(function() return marker_VarSource:GetPos() end)
        if ok then
            pos_VarSource = result
        end
    end
    if pos_VarSource == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_VarSource = result
            end
        end
    end
    if pos_VarSource ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_VarSource, "VarSource") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for VarSource")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_VarListener = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_VarListener = nil
    if marker_VarListener ~= nil and marker_VarListener.GetPos ~= nil then
        local ok, result = pcall(function() return marker_VarListener:GetPos() end)
        if ok then
            pos_VarListener = result
        end
    end
    if pos_VarListener == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_VarListener = result
            end
        end
    end
    if pos_VarListener ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_VarListener, "VarListener") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for VarListener")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local VarSource = Quest:GetThingWithScriptName("VarSource")
    if VarSource ~= nil then
        Quest:SetThingHasInformation(VarSource, true)
        Quest:MiniMapAddMarker(VarSource, "VarSource")
    end

    Quest:Log("VarExternalFlowQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "VarExternalFlowQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "VarExternalFlowQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:SetStateBool("FQT_StopActions", true)
            Quest:Pause(0.1)
            if not Quest:NewScriptFrame() then break end
            Quest:Log("VarExternalFlowQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local VarSource = Quest:GetThingWithScriptName("VarSource")
            if VarSource ~= nil and not VarSource:IsNull() then
                Quest:ClearThingHasInformation(VarSource)
                Quest:MiniMapRemoveMarker(VarSource)
            end

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("VarExternalFlowQuest", true, false, false)
            Quest:DeactivateQuestLater("VarExternalFlowQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

function ProcessQuestActionQueueOnce()
    local processed = Quest:GetStateInt("FQT_ActionProcessed")
    if processed == nil then processed = 0 end
    local current = Quest:GetStateInt("FQT_ActionCounter")
    if current == nil then current = 0 end
    while processed < current do
        processed = processed + 1
        local action = Quest:GetStateString("FQT_Action_" .. tostring(processed))
        if action ~= nil and action ~= "" then
            local actionType, targetName, markerName = string.match(action, "([^|]+)|([^|]+)|?(.*)")
            if actionType ~= nil and targetName ~= nil then
                if markerName == nil or markerName == "" then
                    markerName = targetName
                end
                local target = Quest:GetThingWithScriptName(targetName)
                if target ~= nil then
                    if actionType == "Highlight" then
                        Quest:SetThingHasInformation(target, true)
                    elseif actionType == "ClearHighlight" then
                        Quest:ClearThingHasInformation(target)
                    elseif actionType == "ShowMarker" then
                        Quest:MiniMapAddMarker(target, markerName)
                    elseif actionType == "HideMarker" then
                        Quest:MiniMapRemoveMarker(target)
                    end
                end
            end
            Quest:SetStateString("FQT_Action_" .. tostring(processed), "")
        end
    end
    Quest:SetStateInt("FQT_ActionProcessed", processed)
end

function ProcessQuestActions(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("FQT_StopActions") then break end
        ProcessQuestActionQueueOnce()
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then break end
    end
end

