using System.Globalization;
using System.Text;
using FableQuestTool.Models;

namespace FableQuestTool.Services;

public sealed class CodeGenerator
{
    public string GenerateQuestScript(QuestProject quest)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine($"-- {quest.Name}.lua");
        sb.AppendLine("-- Generated by FSE Quest Creator Pro");
        sb.AppendLine();
        sb.AppendLine("Quest = nil");
        sb.AppendLine();
        sb.AppendLine("function Init(questObject)");
        sb.AppendLine("    Quest = questObject");
        sb.AppendLine($"    Quest:Log(\"{quest.Name}: Init phase started.\")");
        foreach (string region in quest.Regions)
        {
            sb.AppendLine($"    Quest:AddQuestRegion(\"{quest.Name}\", \"{region}\")");
        }
        foreach (QuestState state in quest.States)
        {
            sb.AppendLine(RenderStateInit(state));
        }
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("function Main(questObject)");
        sb.AppendLine("    Quest = questObject");
        sb.AppendLine($"    Quest:Log(\"{quest.Name}: Main() started.\")");

        if (quest.Entities.Count > 0)
        {
            sb.AppendLine("    -- Bind entity scripts");
            foreach (QuestEntity entity in quest.Entities)
            {
                sb.AppendLine($"    Quest:AddEntityBinding(\"{entity.ScriptName}\", \"{quest.Name}/Entities/{entity.ScriptName}\")");
            }
            sb.AppendLine("    Quest:FinalizeEntityBindings()");
        }

        if (!string.IsNullOrWhiteSpace(quest.QuestCardObject))
        {
            sb.AppendLine($"    Quest:AddQuestCard(\"{quest.QuestCardObject}\", \"{quest.Name}\", false, false)");
        }

        if (!string.IsNullOrWhiteSpace(quest.ObjectiveText))
        {
            sb.AppendLine($"    Quest:SetQuestCardObjective(\"{quest.Name}\", \"{Escape(quest.ObjectiveText)}\", \"{quest.ObjectiveRegion1}\", \"{quest.ObjectiveRegion2}\")");
        }

        if (quest.Rewards.Gold > 0)
        {
            sb.AppendLine($"    Quest:SetQuestGoldReward(\"{quest.Name}\", {quest.Rewards.Gold})");
        }

        if (quest.Rewards.Renown > 0)
        {
            sb.AppendLine($"    Quest:SetQuestRenownReward(\"{quest.Name}\", {quest.Rewards.Renown})");
        }

        if (quest.UseQuestStartScreen)
        {
            string isStory = quest.IsStoryQuest ? "true" : "false";
            string isGold = quest.IsGoldQuest ? "true" : "false";
            sb.AppendLine($"    Quest:KickOffQuestStartScreen(\"{quest.Name}\", {isStory}, {isGold})");
        }

        foreach (QuestThread thread in quest.Threads)
        {
            sb.AppendLine($"    Quest:CreateThread(\"{thread.FunctionName}\", {{ region = \"{thread.Region}\" }})");
        }

        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("function OnPersist(questObject, context)");
        sb.AppendLine("    Quest = questObject");
        foreach (QuestState state in quest.States)
        {
            if (!state.Persist)
            {
                continue;
            }
            sb.AppendLine(RenderPersist(state, quest.Name));
        }
        sb.AppendLine("end");
        sb.AppendLine();

        foreach (QuestThread thread in quest.Threads)
        {
            sb.AppendLine($"function {thread.FunctionName}(questObject)");
            sb.AppendLine("    Quest = questObject");
            sb.AppendLine("    -- TODO: implement thread logic");
            sb.AppendLine("end");
            sb.AppendLine();
        }

        sb.AppendLine("function CompleteQuest()");
        sb.Append(RenderRewards(quest));
        sb.AppendLine($"    Quest:SetQuestAsCompleted(\"{quest.Name}\", true, false, false)");
        sb.AppendLine($"    Quest:DeactivateQuest(\"{quest.Name}\", 60)");
        sb.AppendLine("end");

        return sb.ToString();
    }

    public string GenerateEntityScript(QuestProject quest, QuestEntity entity)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine($"-- {entity.ScriptName}.lua");
        sb.AppendLine($"-- Entity script for {quest.Name}");
        sb.AppendLine("-- Generated by FSE Quest Creator Pro");
        sb.AppendLine();
        sb.AppendLine("local Quest = nil");
        sb.AppendLine("local Me = nil");
        sb.AppendLine();
        sb.AppendLine("function Init(questObject, meObject)");
        sb.AppendLine("    Quest = questObject");
        sb.AppendLine("    Me = meObject");
        if (entity.MakeBehavioral)
        {
            sb.AppendLine("    Me:MakeBehavioral()");
        }
        if (entity.ExclusiveControl)
        {
            sb.AppendLine("    Me:TakeExclusiveControl()");
        }
        else if (entity.AcquireControl)
        {
            sb.AppendLine("    Me:AcquireControl()");
        }
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("function Main(questObject, meObject)");
        sb.AppendLine("    Quest = questObject");
        sb.AppendLine("    Me = meObject");
        sb.AppendLine("    local hero = Quest:GetHero()");
        if (entity.Invulnerable)
        {
            sb.AppendLine("    Quest:EntitySetAsDamageable(Me, false)");
        }
        if (entity.Unkillable)
        {
            sb.AppendLine("    Quest:EntitySetAsKillable(Me, false)");
        }
        if (entity.Persistent)
        {
            sb.AppendLine("    Quest:SetThingPersistent(Me, true)");
        }
        if (entity.KillOnLevelUnload)
        {
            sb.AppendLine("    Me:SetToKillOnLevelUnload(true)");
        }
        sb.AppendLine();
        sb.AppendLine("    while true do");
        sb.AppendLine("        -- TODO: node-driven behavior goes here");
        sb.AppendLine("        if Me:IsNull() then break end");
        sb.AppendLine("        if not Quest:NewScriptFrame(Me) then break end");
        sb.AppendLine("    end");
        sb.AppendLine();
        sb.AppendLine("    Me:ReleaseControl()");
        sb.AppendLine("end");

        return sb.ToString();
    }

    public string GenerateRegistrationSnippet(QuestProject quest)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("-- Add this to your quests.lua file:");
        sb.AppendLine();
        sb.AppendLine($"{quest.Name} = {{");
        sb.AppendLine($"    name = \"{quest.Name}\",");
        sb.AppendLine($"    file = \"{quest.Name}/{quest.Name}\",");
        sb.AppendLine($"    id = {quest.Id},");
        sb.AppendLine();
        sb.AppendLine("    entity_scripts = {");
        int entityId = quest.Id + 1;
        foreach (QuestEntity entity in quest.Entities)
        {
            sb.AppendLine($"        {{ name = \"{entity.ScriptName}\", file = \"{quest.Name}/Entities/{entity.ScriptName}\", id = {entityId} }},");
            entityId++;
        }
        sb.AppendLine("    }");
        sb.AppendLine("},");

        return sb.ToString();
    }

    private static string RenderStateInit(QuestState state)
    {
        string name = state.Name;
        string value = FormatLuaValue(state.Type, state.DefaultValue);
        return state.Type switch
        {
            "int" => $"    Quest:SetStateInt(\"{name}\", {value})",
            "string" => $"    Quest:SetStateString(\"{name}\", {value})",
            _ => $"    Quest:SetStateBool(\"{name}\", {value})"
        };
    }

    private static string RenderPersist(QuestState state, string questName)
    {
        string key = $"{questName}_{state.Name}";
        return state.Type switch
        {
            "int" => $"    Quest:SetStateInt(\"{state.Name}\", Quest:PersistTransferInt(context, \"{key}\", Quest:GetStateInt(\"{state.Name}\")))",
            "string" => $"    Quest:SetStateString(\"{state.Name}\", Quest:PersistTransferString(context, \"{key}\", Quest:GetStateString(\"{state.Name}\")))",
            _ => $"    Quest:SetStateBool(\"{state.Name}\", Quest:PersistTransferBool(context, \"{key}\", Quest:GetStateBool(\"{state.Name}\")))"
        };
    }

    private static string RenderRewards(QuestProject quest)
    {
        StringBuilder sb = new StringBuilder();
        if (quest.Rewards.Gold > 0)
        {
            sb.AppendLine($"    Quest:GiveHeroGold({quest.Rewards.Gold})");
        }
        if (quest.Rewards.Experience > 0)
        {
            sb.AppendLine($"    Quest:GiveHeroExperience({quest.Rewards.Experience})");
        }
        if (quest.Rewards.Renown > 0)
        {
            sb.AppendLine($"    Quest:GiveHeroRenownPoints({quest.Rewards.Renown})");
        }
        if (Math.Abs(quest.Rewards.Morality) > 0.001f)
        {
            string value = quest.Rewards.Morality.ToString("0.###", CultureInfo.InvariantCulture);
            sb.AppendLine($"    Quest:GiveHeroMorality({value})");
        }
        foreach (string item in quest.Rewards.Items)
        {
            if (!string.IsNullOrWhiteSpace(item))
            {
                sb.AppendLine($"    Quest:GiveHeroObject(\"{item}\", 1)");
            }
        }
        foreach (string ability in quest.Rewards.Abilities)
        {
            if (!string.IsNullOrWhiteSpace(ability))
            {
                sb.AppendLine($"    Quest:GiveHeroAbility({ability}, true)");
            }
        }
        return sb.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\"", "\\\"");
    }

    private static string FormatLuaValue(string type, object? value)
    {
        if (type == "string")
        {
            string text = value?.ToString() ?? string.Empty;
            return $"\"{Escape(text)}\"";
        }

        if (type == "int")
        {
            if (value is int intValue)
            {
                return intValue.ToString(CultureInfo.InvariantCulture);
            }

            if (int.TryParse(value?.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out int parsed))
            {
                return parsed.ToString(CultureInfo.InvariantCulture);
            }

            return "0";
        }

        if (value is bool boolValue)
        {
            return boolValue ? "true" : "false";
        }

        if (bool.TryParse(value?.ToString(), out bool parsedBool))
        {
            return parsedBool ? "true" : "false";
        }

        return "false";
    }
}
