//-----------------------------------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------ALL FUNCTIONS FOR FABLE SCRIPT EXTENDER-----------------------------------------------------------
//------------------------------------------------------------ENTITY-API-------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------

    void AcquireControl(CScriptThing* pMe);
    void ReleaseControl();
    void MoveToThing_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, float radius, int moveType);
    void PlayAnimation_NonBlocking(CScriptThing* pMe, const std::string& animName,sol::optional<bool> stayOnLastFrame, sol::optional<bool> allowLooking);
    void PlayLoopingAnimation_NonBlocking(CScriptThing* pMe, const std::string& animName, int loopCount, sol::optional<bool> useMovement, sol::optional<bool> allowLooking);
    void PlayCombatAnimation_NonBlocking(CScriptThing* pMe, const std::string& animName, sol::optional<bool> allowLooking);
    void MoveToPosition_NonBlocking(CScriptThing* pMe, sol::table position, float radius, int moveType);
    void FollowThing_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, float distance, bool avoidObstacles);
    void ClearCommands_NonBlocking(CScriptThing* pMe);
    void StopFollowingThing_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing);
    void FollowPreCalculatedRoute_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spRoute,int moveType, sol::optional<bool> avoidObstacles,sol::optional<bool> ignorePathPreferability);
    void MoveToAndPickUpGenericBox_NonBlocking(CScriptThing* pMe, CScriptThing* pBox, int moveType, sol::optional<bool> avoidObstacles);
    void DropGenericBox_NonBlocking(CScriptThing* pMe);
    void Wait_NonBlocking(CScriptThing* pMe, float seconds);
    void WaitForEntityToFinishPerformingTasks_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetEntity);
    void ClearAllActions_NonBlocking(CScriptThing* pMe);
    void ClearAllActionsIncludingLoopingAnimations_NonBlocking(CScriptThing* pMe);
    void UnsheatheWeapons_NonBlocking(CScriptThing* pMe);
    void SummonerLightningOrbAttackTarget_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing);
    void FireProjectileWeaponAtTarget_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing);
    void Speak_Blocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, const std::string& dialogueKey,int selectionMethod, bool makeTargetListen, bool soundIn2D, bool overScreenFade);
    void Converse_NonBlocking(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, const std::string& dialogueKey);
    void SpeakAndWait(CScriptThing* pMe, const std::string& dialogueKey, int selectionMethod = GROUP_SELECT_RANDOM_NO_REPEAT);
    void GainControlAndSpeak(CScriptThing* pMe, const std::string& dialogueKey, int selectionMethod = GROUP_SELECT_RANDOM_NO_REPEAT);
    void MakeBehavioral(CScriptThing* pMe);
    void SetReadableText(CScriptThing* pMe, const std::string& textTag);
    void TakeExclusiveControl(CScriptThing* pMe);
    void MoveToPosition(CScriptThing* pMe, sol::table position, float radius, int moveType);
    void MoveToThing(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, float radius, int moveType);
    void ClearCommands(CScriptThing* pMe);
    void PerformExpression(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, const std::string& expressionName);
    void PlayAnimation(CScriptThing* pMe, const std::string& animName, sol::optional<bool> waitForFinish, sol::optional<bool> stayOnLastFrame, sol::optional<bool> allowLooking);
    void PlayCombatAnimation(CScriptThing* pMe, const std::string& animName, sol::optional<bool> waitForFinish, sol::optional<bool> allowLooking);
    void PlayLoopingAnimation(CScriptThing* pMe, const std::string& animName, int loopCount, sol::optional<bool> waitForFinish, sol::optional<bool> useMovement, sol::optional<bool> allowLooking);
    void MoveToAndPickUpGenericBox(CScriptThing* pMe, CScriptThing* pBox, int moveType, sol::optional<bool> avoidObstacles);
    void DropGenericBox(CScriptThing* pMe);
    void UnsheatheWeapons(CScriptThing* pMe);
    void Wait(CScriptThing* pMe, float seconds);
    void FollowThing(CScriptThing* pMe, const std::shared_ptr<CScriptThing>& spTargetThing, float distance, bool avoidObstacles);
    void StopFollowingThing(CScriptThing* pMe, CScriptThing* pTargetThing);
    void SetAsUsable(CScriptThing* pMe, bool isUsable);
    void SetFriendsWithEverythingFlag(CScriptThing* pMe, bool isFriends);
    void SetActivationTriggerStatus(CScriptThing* pMe, bool isActive);
    void SetToKillOnLevelUnload(CScriptThing* pMe, bool shouldKill);
    bool IsFollowActionRunning_NonBlocking(CScriptThing* pMe, sol::object target_obj);
    bool IsPerformingScriptTask();
    bool IsTalkedToByHero(CScriptThing* pMe);
    bool IsNull(CScriptThing* pMe);
    bool IsKilledByHero(CScriptThing* pMe);
    bool IsAwareOfHero(CScriptThing* pMe);
    bool IsAlive(CScriptThing* pMe);
    bool IsDead(CScriptThing* pMe);
    bool IsFollowActionRunning(CScriptThing* pMe, CScriptThing* pTargetThing);
    bool IsFollowingThing(CScriptThing* pMe);
    bool IsUnconscious(CScriptThing* pMe);
    bool IsOpenDoor(CScriptThing* pMe);
    bool IsSneaking(CScriptThing* pMe);
    bool MsgIsHitByHeroWithFlourish(CScriptThing* pMe);
    bool MsgIsHitByHeroWithDecapitate(CScriptThing* pMe);
    bool MsgIsHitByHeroWithWeapon(CScriptThing* pMe, const std::string& weaponName);
    bool MsgIsUsedByHero(CScriptThing* pMe);
    bool MsgIsTriggeredByHero(CScriptThing* pMe);
    bool MsgIsKnockedOutByHero(CScriptThing* pMe);
    bool MsgPerformedSpecialAbility(CScriptThing* pMe, int abilityEnum);
    bool MsgPerformedAnySpecialAbility(CScriptThing* pMe);
    bool MsgPerformedAnyAggressiveSpecialAbility(CScriptThing* pMe);
    bool MsgPerformedAnyNonAggressiveSpecialAbility(CScriptThing* pMe);
    bool MsgReceivedInventoryItem(CScriptThing* pMe);
    bool MsgIsHitByHeroSpecialAbility(CScriptThing* pMe, int abilityEnum);
    bool MsgOpenedChest(CScriptThing* pMe);
    bool MsgIsKicked(CScriptThing* pMe);
    bool MsgIsPresentedWithItem(CScriptThing* pMe, sol::this_state s);
    bool MsgIsHitByHero(CScriptThing* pMe);
    bool MsgIsHitByAnySpecialAbilityFromHero(CScriptThing* pMe);
    bool MsgIsHitByHealLifeFromHero(CScriptThing* pMe);
    bool MsgIsKilledBy(CScriptThing* pMe, const std::string& killerName);
    std::string GetDataString(CScriptThing* pMe);
    std::string GetCurrentMapName(CScriptThing* pMe);
    std::string GetHomeMapName(CScriptThing* pMe);
    std::string GetDefName(CScriptThing* pMe);
    sol::table GetPos(CScriptThing* pMe, sol::this_state s);
    sol::table GetHomePos(CScriptThing* pMe, sol::this_state s);
    std::shared_ptr<CScriptThing> MsgWhoKilledMe(CScriptThing* pMe);
    std::shared_ptr<CScriptThing> MsgWhoHitMe(CScriptThing* pMe);
    sol::object MsgIsHitByHeroWithProjectileWeapon(CScriptThing* pMe, sol::this_state s);
    sol::object MsgExpressionPerformedTo(CScriptThing* pMe, sol::this_state s);
    sol::object MsgReceivedMoney(CScriptThing* pMe, sol::this_state s);
    int MsgHowLongWasExpressionPerformed(CScriptThing* pMe);
	
//-----------------------------------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------ALL FUNCTIONS FOR FABLE SCRIPT EXTENDER-----------------------------------------------------------
//------------------------------------------------------------QUEST-API--------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------

	void Log(const std::string& message);
	void CreateThread(const std::string& luaFunctionName, sol::table args);
	void ShowMessage(const std::string& message, float duration);
	void ActivateQuest(const std::string& questName);
	void AddQuestCard(const std::string& questCardObjectName, const std::string& questScriptName, bool replayable, bool skip_GM_message);
	void SetHeroGuideShowsQuestCards(bool show);
	void GiveQuestCardDirectly(const std::string& textDBEntry, const std::string& questName, bool flag);
	void SetQuestGoldReward(const std::string& questName, int amount);
	void SetQuestRenownReward(const std::string& questName, int amount);
	void SetQuestCardObjective(const std::string& questName, const std::string& objectiveText, const std::string& region1, const std::string& region2);
	void KickOffQuestStartScreen(const std::string& questName, bool isStory, bool isGold);
	void AddQuestRegion(const std::string& questName, const std::string& regionName);
	void DeactivateQuest(const std::string& questName, unsigned int delay);
	void Pause(float duration);
	void PlayCutscene(const std::string& cutsceneName, sol::table actors);
	void FixMovieSequenceCamera(bool isFixed);
	void PauseAllNonScriptedEntities(bool isPaused);
	void AddEntityBinding(const std::string& entityScriptName, const std::string& scriptFileName);
	void FinalizeEntityBindings();
	void SetCreatureGeneratorsEnabled(const std::string& regionName, bool enabled);
	void EntitySetStockItemPrice(CScriptThing* pThing, int price);
	void EntitySetAsForSale(CScriptThing* pThing, bool bForSale);
	void GiveHeroItem(CScriptThing* pItemThing);
	void EntitySetAppearanceSeed(CScriptThing* pThing, unsigned int seed);
	void ShowOnScreenMessageWithFont(sol::table position, const std::string& message, sol::table color, const std::string& fontName);
	void EntitySetTargetable(CScriptThing* pThing, bool isTargetable);
	void EntityTeleportToThing(CScriptThing* pThingToMove, CScriptThing* pTargetThing);
	void EntitySetAsDrawable(CScriptThing* pThing, bool isDrawable);
	void GiveHeroObject(const std::string& objectDefName, int amount);
	void RemoveThing(CScriptThing* pThing);
	void EntitySetAllStategroupsEnabled(CScriptThing* pThing, bool enabled);
	void SetQuestWorldMapOffset(const std::string& questName, int x, int y);
	void EntitySetAsKillable(CScriptThing* pThing, bool isKillable);
	void EntitySetOpinionReactionMask(CScriptThing* pThing, const std::string& maskName);
	void SetThingHasInformation(CScriptThing* pThing, bool hasInfo);
	void EntitySetFacingAngleTowardsThing(CScriptThing* pThing, CScriptThing* pTarget);
	void TakeObjectFromHero(const std::string& objectDefName);
	void GiveHeroGold(int amount);
	void GiveHeroMorality(float amount);
	void GiveHeroExperience(int amount);
	void ClearThingHasInformation(CScriptThing* pThing);
	void FadeScreenOut(float fadeTime, float holdTime);
	void FadeScreenIn();
	void HeroReceiveMessageFromGuildMaster(const std::string& messageKey, const std::string& graphicName, bool highPriority, bool alwaysPlay);
	void OverrideMusic(int musicSetType, bool isCutscene, bool forcePlay);
	void ShowMessageWithButtons(const std::string& message, const std::string& button1Response, const std::string& button2Response, float displayTime);
	void SetTimer(int timerId, int timeValue);
	void SetQuestAsFailed(const std::string& questName, bool showScreen, const std::string& wideMessage, bool useWideMessage);
	void StopOverrideMusic(bool isCutscene);
	void ResetPlayerCreatureCombatMultiplier();
	void SetQuestAsCompleted(const std::string& questName, bool showScreen, bool updateLogbook, bool showQuestCompleteScreen);
	void DeactivateQuestLater(const std::string& questName, unsigned int delayFrames);
	void AddRumourCategory(const std::string& categoryName);
	void AddNewRumourToCategory(const std::string& categoryName, const std::string& rumourTextKey);
	void AddGossipFactionToCategory(const std::string& categoryName, const std::string& factionName);
	void EntitySetCutsceneBehaviour(CScriptThing* pThing, int behaviour);
	void CameraDefault();
	void EntitySetInFaction(CScriptThing* pThing, const std::string& factionName);
	void SetThingPersistent(CScriptThing* pThing, bool isPersistent);
	void EntitySetAsDamageable(CScriptThing* pThing, bool isDamageable);
	void EntitySetAsToAddToComboMultiplierWhenHit(CScriptThing* pThing, bool doesAddToCombo);
	void SetRegionExitAsActive(CScriptThing* pThing, bool isActive);
	void EntityFadeOut(CScriptThing* pThing, float duration);
	void OpenDoor(CScriptThing* pThing);
	void EntitySetThingAsEnemyOfThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	void ChangeHeroHealthBy(float amount, bool canKill, bool showChange);
	void CameraShake(float intensity, float duration);
	void GiveHeroAbility(int abilityId, bool give);
	void SetBeerRequestPhrase(const std::shared_ptr<CScriptThing>& spThing, unsigned int phraseID);
	void ResetBeerRequestPhrase(const std::shared_ptr<CScriptThing>& spThing);
	void SetScriptingStateGroup(const std::shared_ptr<CScriptThing>& spThing, int eGroup);
	void ResetScriptingStateGroup(const std::shared_ptr<CScriptThing>& spThing);
	void SetMaxHeroReactionDistance(const std::shared_ptr<CScriptThing>& spThing, float distance);
	void ResetMaxHeroReactionDistance(const std::shared_ptr<CScriptThing>& spThing);
	void SetActionFrequency(const std::shared_ptr<CScriptThing>& spThing, int frequency);
	void ResetActionFrequency(const std::shared_ptr<CScriptThing>& spThing);
	void SetActionFrequencyVariation(const std::shared_ptr<CScriptThing>& spThing, float variation);
	void ResetActionFrequencyVariation(const std::shared_ptr<CScriptThing>& spThing);
	void SetAction(const std::shared_ptr<CScriptThing>& spThing, const std::string& action);
	void ResetAction(const std::shared_ptr<CScriptThing>& spThing);
	void SetFaceHeroForAction(const std::shared_ptr<CScriptThing>& spThing, bool bFaceHero);
	void ResetFaceHeroForAction(const std::shared_ptr<CScriptThing>& spThing);
	void SetTargetName(const std::shared_ptr<CScriptThing>& spThing, const std::string& targetName);
	void ResetTargetName(const std::shared_ptr<CScriptThing>& spThing);
	void SetFollowDistance(const std::shared_ptr<CScriptThing>& spThing, float distance);
	void ResetFollowDistance(const std::shared_ptr<CScriptThing>& spThing);
	void SetAttackHeroOnSight(const std::shared_ptr<CScriptThing>& spThing, bool bAttack);
	void ResetAttackHeroOnSight(const std::shared_ptr<CScriptThing>& spThing);
	void SetTimeToSpendHarassingHero(const std::shared_ptr<CScriptThing>& spThing, int time);
	void ResetTimeToSpendHarassingHero(const std::shared_ptr<CScriptThing>& spThing);
	void SetCombatNearbyEnemyFleeingBreakOffRange(const std::shared_ptr<CScriptThing>& spThing, float range);
	void ResetCombatNearbyEnemyFleeingBreakOffRange(const std::shared_ptr<CScriptThing>& spThing);
	void SetCombatNearbyBreakOffRange(const std::shared_ptr<CScriptThing>& spThing, float range);
	void ResetCombatNearbyBreakOffRange(const std::shared_ptr<CScriptThing>& spThing);
	void SetStealStealableItems(const std::shared_ptr<CScriptThing>& spThing, bool bSteal);
	void ResetStealStealableItems(const std::shared_ptr<CScriptThing>& spThing);
	void SetRecoverStealableItems(const std::shared_ptr<CScriptThing>& spThing, bool bRecover);
	void ResetRecoverStealableItems(const std::shared_ptr<CScriptThing>& spThing);
	void SetTakeStealableItemToRandomDestination(const std::shared_ptr<CScriptThing>& spThing, bool bRandom);
	void ResetTakeStealableItemToRandomDestination(const std::shared_ptr<CScriptThing>& spThing);
	void SetKillSelfAndStealableItemAfterReachingDestination(const std::shared_ptr<CScriptThing>& spThing, bool bKill);
	void ResetKillSelfAndStealableItemAfterReachingDestination(const std::shared_ptr<CScriptThing>& spThing);
	void SetAllowedToFollow(const std::shared_ptr<CScriptThing>& spThing, bool bAllowed);
	void ResetAllowedToFollow(const std::shared_ptr<CScriptThing>& spThing);
	void SetTableName(const std::shared_ptr<CScriptThing>& spThing, const std::string& tableName);
	void ResetTableName(const std::shared_ptr<CScriptThing>& spThing);
	void SetSeatName(const std::shared_ptr<CScriptThing>& spThing, const std::string& seatName);
	void ResetSeatName(const std::shared_ptr<CScriptThing>& spThing);
	void SetDisableHeadLooking(const std::shared_ptr<CScriptThing>& spThing, bool bDisabled);
	void ResetDisableHeadLooking(const std::shared_ptr<CScriptThing>& spThing);
	void SetIsPushableByHero(const std::shared_ptr<CScriptThing>& spThing, bool bIsPushable);
	void ResetIsPushableByHero(const std::shared_ptr<CScriptThing>& spThing);
	void SetLookForFiniteTime(const std::shared_ptr<CScriptThing>& spThing, bool bFinite);
	void ResetLookForFiniteTime(const std::shared_ptr<CScriptThing>& spThing);
	void SetAvoidRegionExits(const std::shared_ptr<CScriptThing>& spThing, bool bAvoid);
	void ResetAvoidRegionExits(const std::shared_ptr<CScriptThing>& spThing);
	void SetTargetingDistanceOffset(const std::shared_ptr<CScriptThing>& spThing, float offset);
	void ResetTargetingDistanceOffset(const std::shared_ptr<CScriptThing>& spThing);
	void SetPlayerUsingMeleeDummies(bool bIsUsing);
	void SetPlayerUsingRangedDummies(bool bIsUsing);
	void SetPlayerUsingWillDummies(bool bIsUsing);
	void SetCheapHeadLooking(bool bIsCheap);
	void SetQuitTavernGame(bool bQuit);
	void SetPrizeTavernTable(bool bIsPrize);
	void SetBettingActive(bool bIsActive);
	void SetBettingAccept(bool bAccept);
	void SetBettingAmount(int amount);
	void SetCountBetMoneyDown(bool bCount);
	void SetSpotTheAdditionBeaten(bool bBeaten);
	void SetGlobalTargetingDistanceOffset(float offset);
	void SetTradingPriceMult(float mult);
	void SetBoastingEnabled(bool bIsEnabled);
	void SetActiveGossipCategories(const std::string& category, bool isActive);
	void ClearActiveGossipCategories();
	void ClearIsGossipForPlayer();
	void SetGossip(const std::string& category, const std::string& rumour, int index);
	void ClearGossip(const std::string& category);
	void RemoveGossip(const std::string& category);
	void AddGossip(const std::string& category);
	void AddGossip(const std::string& category, const std::string& rumour);
	void DeregisterTimer(int timerId);
	void SetStateBool(const std::string& key, bool value);
	void SetStateInt(const std::string& key, int value);
	void SetStateString(const std::string& key, const std::string& value);
	void SetGlobalBool(const std::string& key, bool value);
	void SetGlobalInt(const std::string& key, int value);
	void SetGlobalString(const std::string& key, const std::string& value);
	void ReleaseThing(CScriptThing* pThing);
	void LogReceivedPointer(CScriptThing* pThing, const std::string& context);
	void StartMovieSequence();
	void EndMovieSequence();
	void AddLineToConversation(int conversationID, const std::string& textKey, const std::shared_ptr<CScriptThing>& spSpeaker,
		const std::shared_ptr<CScriptThing>& spListener, sol::optional<bool> showSubtitle);
	void RemoveConversation(int conversationID, sol::optional<bool> cutOffSpeech);
	void DontPopulateNextLoadedRegion();
	void DisplayQuestInfo(bool bDisplay);
	void SetQuestInfoName(const std::string& name);
	void SetQuestInfoText(const std::string& text);
	void UpdateQuestInfoCounter(int elementID, int count, int max);
	void AddScreenMessage(const std::string& message, sol::optional<int> selectionMethod);
	void ClearAllRumbles();
	void AddScreenTitleMessage(const std::string& message, float duration, sol::optional<bool> bUnknown);
	void DisplayGameInfo(const std::string& infoKey);
	void DisplayGameInfoText(const std::string& wideText);
	void GiveHeroWeapon(const std::string& weaponDefName, bool bEquip);
	void SetWeaponAsHerosActiveWeapon(const std::string& weaponDefName);
	void SetHeroAbleToGainExperience(bool bCanGain);
	void SheatheHeroWeapons();
	void SetHeroWillAsUsable(bool bIsUsable);
	void SetHeroWeaponsAsUsable(bool bIsUsable);
	void SetWeaponOutCrimeEnabled(bool bIsEnabled);
	void SetGuardsIgnoreCrimes(bool bDoIgnore);
	void RemoveAllHeroWeapons();
	void ConfiscateAllHeroItems();
	void ConfiscateAllHeroWeapons();
	void ConfiscateItemsOfTypeFromHero(const std::string& defName);
	void ReturnAllConfiscatedItemsToHero();
	void MakeHeroCarryItemInHand(const std::shared_ptr<CScriptThing>& spThing, bool setAsActive, bool setAsPersistent);
	void MakeHeroCarryItemInHand(const std::string& defName);
	void AddTattooToHero(const std::string& tattooDefName);
	void SetPlayerCreatureOnlyTarget(const std::shared_ptr<CScriptThing>& spTarget);
	void ResetPlayerCreatureOnlyTarget();
	void ChangeHeroMoralityDueToTheft();
	void ChangeHeroMoralityDueToPicklock();
	void GiveHeroRenownPoints(int amount);
	void IncreaseHeroRenownLevel();
	void SetHeroAge(float age);
	void SetHeroAsTeenager(bool bIsTeen);
	void SetHeroAsApprentice(bool bIsApprentice);
	void SetHeroWillEnergyLevel(float level);
	void SetHeroWillEnergyAsAbleToRefill(bool bCanRefill);
	void SetHeroHandLampAsLit(bool bIsLit);
	void RemoveHeroClothing();
	void SetHeroAsWearing(const std::string& clothingDefName);
	void ChangeHeroHairstyle(const std::string& hairstyleDefName);
	void RemoveHeroHairstyle();
	void ApplyHeroPenaltyForDeath();
	void GiveHeroTitle(const std::string& titleKey);
	void EntitySetAsMarryable(const std::shared_ptr<CScriptThing>& spThing, bool bIsMarryable);
	void EntitySetAsAbleToRegionFollowWhenMarried(const std::shared_ptr<CScriptThing>& spThing, bool bCanFollow);
	void EntityForceMarriageToHero(const std::shared_ptr<CScriptThing>& spThing, bool bIsForced);
	void SetNumberOfTimesHeroHasHadSex(int count);
	void SetHeroAsHavingHadSex(bool bHasHadSex);
	void SetHeroAsHavingHadGaySex(bool bHasHadGaySex);
	void GiveThingHeroRewardItem(const std::shared_ptr<CScriptThing>& spThing, const std::string& pItemDefName, const std::string& pBoneName);
	void GiveThingItemInHand(const std::shared_ptr<CScriptThing>& spThing, const std::string& pItemDefName, bool bShow);
	void GiveThingItemInSlot(const std::shared_ptr<CScriptThing>& spThing, const std::string& pItemDefName, const std::string& pSlotName);
	void GiveHeroExpression(const std::string& pExpressionName, int level, sol::optional<bool> bShowPopup);
	void EntitySetAsAllowedToFollowHero(const std::shared_ptr<CScriptThing>& spThing, bool bIsAllowed);
	void EntitySetAsAllowedToChangeRegionFollowingState(const std::shared_ptr<CScriptThing>& spThing, bool bIsAllowed);
	void EntitySetAsRespondingToFollowAndWaitExpressions(const std::shared_ptr<CScriptThing>& spThing, bool bDoesRespond);
	void EntitySetAsMirroringHeroEnemyRelationsWhileFollowing(const std::shared_ptr<CScriptThing>& spThing, bool bDoesMirror);
	void TeleportAllFollowersToHeroPosition();
	void EntityTeleportToHeroPosition(const std::shared_ptr<CScriptThing>& spThing);
	void SendEntityEvent(int eventType, const std::shared_ptr<CScriptThing>& spSender, const std::shared_ptr<CScriptThing>& spReceiver);
	void ModifyThingHealth(const std::shared_ptr<CScriptThing>& spThing, float amount, sol::optional<bool> bUnknown);
	void EntitySetMaxHealth(const std::shared_ptr<CScriptThing>& spThing, float maxHealth, bool bSetCurrentToMax);
	void SetThingAsKilled(const std::shared_ptr<CScriptThing>& spThing);
	void GiveHeroNewQuestObjective(const std::string& pObjectiveText, unsigned int objectiveID);
	void TellHeroQuestObjectiveCompleted(unsigned int objectiveID);
	void TellHeroQuestObjectiveFailed(unsigned int objectiveID);
	void SetGuildMasterMessages(bool bAreEnabled);
	void SetQuestAsPersistent(const std::string& questName, bool bIsPersistent);
	void RemoveQuestCardFromGuild(const std::string& questName);
	void RemoveQuestCardFromHero(const std::string& questName);
	void RemoveAllAvailableQuestCardsFromGuild();
	void FailAllActiveQuests();
	void AddFeatCard(int featID, const std::string& name, const std::string& description);
	void AddBoast(const std::string& questName, int boastID, int renown, int gold, bool bIsBoast, const std::string& boastText, int textID);
	void RemoveBoast(int boastID, const std::string& questName);
	void SetBoastAsFailed(int boastID, const std::string& questName);
	void SetBoastAsCompleted(int boastID, const std::string& questName);
	void KickOffDeathScreen();
	void KickOffCreditsScreen(const std::string& creditsName);
	void SetPreferredQuickAccessItem(const std::string& itemName, int dPadDirection, int slot);
	void SetDeathRecoveryMarkerName(const std::string& markerName);
	void ResetDeathRecoveryMarkerNameToDefault();
	void SetWhetherToFailQuestOnDeath(bool bShouldFail);
	void ResetWhetherToFailQuestOnDeathToDefault();
	void UpdateQuestInfoBar(int id, float current, float max, float scale);
	void ChangeQuestInfoBarColour(int id, sol::table color1, sol::table color2);
	void UpdateQuestInfoTimer(int id, float scale);
	void UpdateQuestInfoCounterList(int id, int count, int max);
	void UpdateQuestInfoTick(int id, bool bState);
	void RemoveQuestInfoElement(int id);
	void RemoveAllQuestInfoElements();
	void DisplayTime(bool bDisplay);
	void DisplayMoneyBag(bool bDisplay);
	void DisplayMiniGameInfo(bool bDisplay, int gameType);
	void UpdateMiniGameInfoBar(float value);
	void EntitySetAsPickPocketed(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetAsPickLocked(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetAsStolen(const std::shared_ptr<CScriptThing>& spThing);
	void MiniMapAddMarker(const std::shared_ptr<CScriptThing>& spThing, const std::string& markerName);
	void MiniMapSetMarkerGraphic(const std::shared_ptr<CScriptThing>& spThing, const std::string& graphicName);
	void MiniMapRemoveMarker(const std::shared_ptr<CScriptThing>& spThing);
	void MiniMapRemoveAllMarkers();
	void MiniMapAllowRouteBetweenRegions(const std::string& region1, const std::string& region2, bool bAllow);
	void MiniMapSetAsEnabled(bool bIsEnabled);
	void EntitySetAsHiddenOnMiniMap(const std::shared_ptr<CScriptThing>& spThing, bool bIsHidden);
	void SetHUDEnabled(bool bIsEnabled);
	void EntitySetWillBeUsingNarrator(const std::shared_ptr<CScriptThing>& spThing, const std::string& dialogueKey);
	void EntityResetAsPureAINarrator(const std::shared_ptr<CScriptThing>& spThing);
	void PlayAVIMovie(const std::string& movieName);
	void FadeScreenOutUntilNextCallToFadeScreenIn(float fadeTime, float holdTime);
	void EndCutFade();
	void EndLetterBox();
	void PauseAllEntities(bool bIsPaused);
	void SetAllowScreenFadingOnNextRegionChange(bool bIsAllowed);
	void SetAllowScreenFadingIfAlreadyFaded(bool bIsAllowed);
	void SetAbilityAvailability(int ability, bool bIsAvailable);
	void SetEnvironmentalEffectsAlwaysUpdate(bool bAlwaysUpdate);
	void SetDeadCreaturesAndExperienceOrbsAndDropBagsAsHidden(bool bIsHidden);
	void RemoveDeadCreature(const std::string& creatureName);
	void CameraSetCameraPreloadFlag(bool bPreload);
	void CameraCircleAroundThing(const std::shared_ptr<CScriptThing>& spThing, sol::table offset, float duration);
	void CameraCircleAroundPos(sol::table pos, sol::table offset, float duration);
	void CameraMoveToPosAndLookAtPos(sol::table camPos, sol::table targetPos, float duration);
	void CameraMoveToPosAndLookAtThing(sol::table camPos, const std::shared_ptr<CScriptThing>& spTargetThing, float duration);
	void CameraMoveBetweenLookingAt(const std::shared_ptr<CScriptThing>& spTargetThing, sol::table startPos, sol::table endPos, float f1, float f2);
	void CameraMoveBetweenLookingAt(sol::table targetPos, sol::table startPos, sol::table endPos, float f1, float f2);
	void CameraMoveBetweenLookFromAndLookTo(sol::table startFrom, sol::table startTo, sol::table endFrom, sol::table endTo, float duration);
	void CameraUseCameraPoint(const std::shared_ptr<CScriptThing>& spCamPoint, const std::shared_ptr<CScriptThing>& spTarget, float duration, int i1, int i2);
	void CameraUseCameraPoint(const std::string& camPointName, const std::shared_ptr<CScriptThing>& spTarget, float duration, int i1, int i2);
	void CameraResetToViewBehindHero(float duration);
	void CameraUseScreenEffect(float f1, float f2, float f3);
	void CameraCancelScreenEffect();
	void CameraEarthquakeIntensityAtPos(sol::table pos, float intensity, float duration);
	void CameraUseCameraPoint(const std::shared_ptr<CScriptThing>& spCamPoint, sol::table offset, sol::table rotation, float duration, int i1, int i2);
	void CameraUseCameraPoint(const std::string& camPointName, sol::table offset, sol::table rotation, float duration, int i1, int i2);
	void CameraDoConversation(const std::shared_ptr<CScriptThing>& spSpeaker, const std::shared_ptr<CScriptThing>& spListener, int eOp, sol::optional<bool> bUnknown);
	void CloseChest(const std::shared_ptr<CScriptThing>& spChest);
	void DisplayLockedChestMessage(const std::shared_ptr<CScriptThing>& spChest);
	void SetTrophyAsMountable(const std::shared_ptr<CScriptThing>& spTrophy, bool bIsMountable);
	void SetVillageLimbo(const std::shared_ptr<CScriptThing>& spVillage, bool bIsInLimbo);
	void SetCreatureNotReload(const std::shared_ptr<CScriptThing>& spCreature);
	void EnableGuards(const std::shared_ptr<CScriptThing>& spVillage, bool bIsEnabled);
	void EnableVillagerDefTypes(const std::shared_ptr<CScriptThing>& spVillage, bool bIsEnabled, const std::string& defName);
	void ClearHeroEnemyOfGuards(const std::shared_ptr<CScriptThing>& spVillage);
	void SetThingAsUsable(const std::shared_ptr<CScriptThing>& spThing, bool bIsUsable);
	void SetThingHomeBuilding(const std::shared_ptr<CScriptThing>& spThing, const std::shared_ptr<CScriptThing>& spHouse);
	void GiveThingBestEnemyTarget(const std::shared_ptr<CScriptThing>& spThing, const std::shared_ptr<CScriptThing>& spTarget);
	void ClearThingBestEnemyTarget(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetInLimbo(const std::shared_ptr<CScriptThing>& spThing, bool bIsInLimbo, sol::optional<bool> bUnknown);
	void AddCrimeCommitted(const std::shared_ptr<CScriptThing>& spVillage, int crimeType, sol::optional<bool> bUnknown, const std::shared_ptr<CScriptThing>& spCriminal, const std::shared_ptr<CScriptThing>& spVictim, int deedType);
	void SetVillageAttitude(const std::shared_ptr<CScriptThing>& spVillage, int eAttitude);
	void EntitySetNegateAllHits(const std::shared_ptr<CScriptThing>& spThing, bool bNegate);
	void EntitySetEvadeAllHits(const std::shared_ptr<CScriptThing>& spThing, bool bEvade);
	void EntitySetAbleToBeEngagedInCombat(const std::shared_ptr<CScriptThing>& spThing, bool bIsAble);
	void EntitySetAlwaysBlockAttacksFromThing(const std::shared_ptr<CScriptThing>& spBlocker, const std::shared_ptr<CScriptThing>& spAttacker, bool bBlock);
	void EntitySetAttackThingImmediately(const std::shared_ptr<CScriptThing>& spAttacker, const std::shared_ptr<CScriptThing>& spTarget, sol::optional<bool> b1, sol::optional<bool> b2);
	void EntitySetCombatType(const std::shared_ptr<CScriptThing>& spThing, const std::string& combatType);
	void EntityResetCombatTypeToDefault(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetMaxNumberOfAttackers(const std::shared_ptr<CScriptThing>& spThing, int maxAttackers);
	void EntityClearMaxNumberOfAttackers(const std::shared_ptr<CScriptThing>& spThing);
	void EntityAttachToScript(const std::shared_ptr<CScriptThing>& spThing, const std::string& questName);
	void EntitySetCombatAbility(const std::shared_ptr<CScriptThing>& spThing, float ability);
	void EntitySetRangedTarget(const std::shared_ptr<CScriptThing>& spThing, const std::shared_ptr<CScriptThing>& spTarget);
	void EntityClearRangedTarget(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetTargetingValidTargetWithoutLOS(const std::shared_ptr<CScriptThing>& spThing, bool bIsValid);
	void EntitySetTargetingType(const std::shared_ptr<CScriptThing>& spThing, int eType);
	void EntityTeleportToPosition(const std::shared_ptr<CScriptThing>& spThing, sol::table pos, float f, sol::optional<bool> b1, sol::optional<bool> b2);
	void EntitySetFacingAngle(const std::shared_ptr<CScriptThing>& spThing, float angle, sol::optional<bool> bUnknown);
	void EntitySetPerceptionVariables(const std::shared_ptr<CScriptThing>& spThing, float f1, float f2, float f3);
	void EntitySetThingAsWantingMoney(const std::shared_ptr<CScriptThing>& spThing, int amount);
	void EntitySetAppearanceMorphSeed(const std::shared_ptr<CScriptThing>& spThing, int seed);
	void SetEntityAsRegionFollowing(const std::shared_ptr<CScriptThing>& spFollower, const std::shared_ptr<CScriptThing>& spTarget, bool bFollow);
	void SetEntityAsFollowingHeroThroughTeleporters(const std::shared_ptr<CScriptThing>& spThing, bool bFollow);
	void EntitySetMaxRunningSpeed(const std::shared_ptr<CScriptThing>& spThing, float speed);
	void EntitySetMaxWalkingSpeed(const std::shared_ptr<CScriptThing>& spThing, float speed);
	void EntityResetMaxRunningSpeed(const std::shared_ptr<CScriptThing>& spThing);
	void EntityResetMaxWalkingSpeed(const std::shared_ptr<CScriptThing>& spThing);
	void EntityAttachToVillage(const std::shared_ptr<CScriptThing>& spThing, const std::shared_ptr<CScriptThing>& spVillage);
	void EntitySetAsSittingOnFloor(const std::shared_ptr<CScriptThing>& spThing, bool bIsSitting);
	void EntitySetAsHavingBoundHands(const std::shared_ptr<CScriptThing>& spThing, bool bIsBound);
	void EntitySetAsRemoveAllMovementBlockingModes(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetAsScared(const std::shared_ptr<CScriptThing>& spThing, bool bIsScared);
	void EntitySetAsDrunk(const std::shared_ptr<CScriptThing>& spThing, bool bIsDrunk);
	void EntityForceToLookAtThing(const std::shared_ptr<CScriptThing>& spLooker, const std::shared_ptr<CScriptThing>& spTarget);
	void EntityForceToLookAtCamera(const std::shared_ptr<CScriptThing>& spLooker, bool bLook);
	void EntityForceToLookAtNothing(const std::shared_ptr<CScriptThing>& spLooker);
	void EntityResetForceToLookAt(const std::shared_ptr<CScriptThing>& spLooker);
	void EntitySetShotAccuracyPercentage(const std::shared_ptr<CScriptThing>& spThing, int accuracy);
	void EntityDropGenericBox(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySheatheWeapons(const std::shared_ptr<CScriptThing>& spThing, sol::optional<bool> bUnknown);
	void EntityUnsheatheWeapons(const std::shared_ptr<CScriptThing>& spThing, sol::optional<bool> bUnknown);
	void EntityUnsheatheMeleeWeapon(const std::shared_ptr<CScriptThing>& spThing, sol::optional<bool> bUnknown);
	void EntityUnsheatheRangedWeapon(const std::shared_ptr<CScriptThing>& spThing, sol::optional<bool> bUnknown);
	void EntitySetAlpha(const std::shared_ptr<CScriptThing>& spThing, float alpha, sol::optional<bool> bUnknown);
	void EntitySetAsAbleToWalkThroughSolidObjects(const std::shared_ptr<CScriptThing>& spThing, bool bCanWalkThrough);
	void EntitySetAsRespondToHit(const std::shared_ptr<CScriptThing>& spThing, bool bDoesRespond);
	void EntitySetAsLocked(const std::shared_ptr<CScriptThing>& spThing, bool bIsLocked);
	void EntityDecapitate(const std::shared_ptr<CScriptThing>& spThing);
	void EntityGiveGold(const std::shared_ptr<CScriptThing>& spThing, int amount);
	void EntitySetAllowBossPhaseChanges(const std::shared_ptr<CScriptThing>& spThing, bool bAllow);
	void EntitySetBossPhase(const std::shared_ptr<CScriptThing>& spThing, int phase);
	void EntityResetCreatureMode(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetAsReceivingEvents(const std::shared_ptr<CScriptThing>& spThing, bool bReceivesEvents);
	void EntitySetAsToAddToStatChangesWhenHit(const std::shared_ptr<CScriptThing>& spThing, bool bAddsToStats);
	void EntityLeaveCombatStance(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetAsUseMovementInActions(const std::shared_ptr<CScriptThing>& spThing, bool bUseMovement);
	void EntitySetAsDisplayingEmoteIcon(const std::shared_ptr<CScriptThing>& spThing, bool bDisplaysIcon);
	void EntitySetAsCollidableToThings(const std::shared_ptr<CScriptThing>& spThing, bool bIsCollidable);
	void EntityEnableGravity(const std::shared_ptr<CScriptThing>& spThing, bool bIsEnabled);
	void EntitySetLightAsOn(const std::shared_ptr<CScriptThing>& spThing, bool bIsOn);
	void EntityFadeIn(const std::shared_ptr<CScriptThing>& spThing, float duration);
	void EntityBeginLoadingAnimation(const std::shared_ptr<CScriptThing>& spThing, const std::string& pAnimName);
	void EntityBeginLoadingBasicAnimations(const std::shared_ptr<CScriptThing>& spThing);
	void EntityCastLightningAtTarget(const std::shared_ptr<CScriptThing>& spCaster, const std::shared_ptr<CScriptThing>& spTarget);
	void BeginLoadingMesh(const std::string& pMeshName);
	void EntityStartScreamerSuperAttackThing(const std::shared_ptr<CScriptThing>& spScreamer, const std::shared_ptr<CScriptThing>& spTarget);
	void EntityEndScreamerSuperAttackThing(const std::shared_ptr<CScriptThing>& spScreamer);
	void SetLightColour(const std::shared_ptr<CScriptThing>& spLight, sol::table color);
	void CreatureGeneratorSetFamily(const std::shared_ptr<CScriptThing>& spGenerator, const std::string& familyName);
	void CreatureGeneratorTrigger(const std::shared_ptr<CScriptThing>& spGenerator);
	void CreatureGeneratorSetAlwaysCreateCreaturesOnTrigger(const std::shared_ptr<CScriptThing>& spGenerator, bool bAlwaysCreate);
	void CreatureGeneratorSetGeneratedCreatureScriptName(const std::shared_ptr<CScriptThing>& spGenerator, const std::string& scriptName);
	void CreatureGeneratorSetNumTriggers(const std::shared_ptr<CScriptThing>& spGenerator, int numTriggers);
	void CreatureGeneratorAddTriggerer(const std::shared_ptr<CScriptThing>& spGenerator, const std::shared_ptr<CScriptThing>& spTriggerer);
	void CreatureGeneratorRemoveTriggerer(const std::shared_ptr<CScriptThing>& spGenerator, const std::shared_ptr<CScriptThing>& spTriggerer);
	void SetCreatureGeneratorEnabled(const std::shared_ptr<CScriptThing>& spGenerator, bool bIsEnabled);
	void SetCreatureGeneratorsEnabledDuringScript(const std::string& regionName, bool bIsEnabled);
	void SetCreatureGeneratorsCreatureGroupAsEnabled(int eGroup, bool bIsEnabled);
	void SetTeleporterAsActive(const std::shared_ptr<CScriptThing>& spTeleporter, bool bIsActive);
	void SetTeleportingAsActive(bool bIsActive);
	void SetRegionEntranceAsActive(const std::shared_ptr<CScriptThing>& spEntrance, bool bIsActive);
	void SetRegionTextDisplayAsActive(bool bIsActive);
	void SetHeroSleepingAsEnabled(bool bIsEnabled);
	void SetExperienceSpendingAsEnabled(bool bIsEnabled);
	void SetMoralityChangingAsEnabled(bool bIsEnabled);
	void SetSummonerDeathExplosionAffectsHero(bool bDoesAffect);
	void SetDiggingSpotAsHidden(const std::shared_ptr<CScriptThing>& spSpot, bool bIsHidden);
	void WaitForCameraMessage(const std::string& message);
	void SetThingAsConscious(const std::shared_ptr<CScriptThing>& spThing, bool bIsConscious, sol::optional<std::string> animName);
	void SetFireToThing(const std::shared_ptr<CScriptThing>& spThing);
	void ExtinguishFiresOnThing(const std::shared_ptr<CScriptThing>& spThing);
	void AddItemToContainer(const std::shared_ptr<CScriptThing>& spContainer, const std::string& itemDefName);
	void RemoveItemFromContainer(const std::shared_ptr<CScriptThing>& spContainer, const std::string& itemDefName);
	void EntitySetDeathContainerAsEnabled(const std::shared_ptr<CScriptThing>& spThing, bool bIsEnabled);
	void EntitySetStategroupEnabled(const std::shared_ptr<CScriptThing>& spThing, const std::string& stateGroupName, bool bEnabled);
	void EntitySetCombatEnabled(const std::shared_ptr<CScriptThing>& spThing, bool bIsEnabled);
	void EntitySetSleepEnabled(const std::shared_ptr<CScriptThing>& spThing, bool bIsEnabled);
	void EntitySetOpinionReactionsEnabled(const std::shared_ptr<CScriptThing>& spThing, bool bEnabled);
	void EntitySetDeedReactionsEnabled(const std::shared_ptr<CScriptThing>& spThing, bool bEnabled);
	void EntityUnsetThingAsEnemyOfThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	void EntitySetThingAsAllyOfThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	void EntityUnsetThingAsAllyOfThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	void SetFactionAsAlliedToFaction(const std::string& faction1, const std::string& faction2);
	void SetFactionAsNeutralToFaction(const std::string& faction1, const std::string& faction2);
	void SetFactionAsEnemyToFaction(const std::string& faction1, const std::string& faction2);
	void EntitySetOpinionReactionMaskByInt(const std::shared_ptr<CScriptThing>& spThing, int mask);
	void EntitySetOpinionDeedMaskByString(const std::shared_ptr<CScriptThing>& spThing, const std::string& maskName);
	void EntitySetOpinionDeedMaskByInt(const std::shared_ptr<CScriptThing>& spThing, int mask);
	void EntitySetOpinionDeedTypeEnabled(const std::shared_ptr<CScriptThing>& spThing, int eDeed, bool bIsEnabled);
	void EntitySetOpinionAttitudeEnabled(const std::shared_ptr<CScriptThing>& spThing, int eAttitude, bool bIsEnabled);
	void EntitySetOpinionReactionEnabled(const std::shared_ptr<CScriptThing>& spThing, int eReaction, bool bIsEnabled);
	void EntitySetPersonalityOverrideByInt(const std::shared_ptr<CScriptThing>& spThing, int personality);
	void EntitySetPersonalityOverrideByString(const std::shared_ptr<CScriptThing>& spThing, const std::string& personalityName);
	void EntityClearPersonalityOverride(const std::shared_ptr<CScriptThing>& spThing);
	void EntitySetAsOpinionSourceByInt(const std::shared_ptr<CScriptThing>& spThing, int sourceID);
	void EntitySetAsOpinionSourceByString(const std::shared_ptr<CScriptThing>& spThing, const std::string& sourceName);
	void EntityUnsetAsOpinionSource(const std::shared_ptr<CScriptThing>& spThing, sol::optional<bool> bUnknown);
	void OpinionSourceSetAsExclusive(const std::shared_ptr<CScriptThing>& spSource, bool bIsExclusive);
	void OpinionSourceSetAsAttentionGrabbing(const std::shared_ptr<CScriptThing>& spSource, bool bIsGrabbing);
	void EntityPostOpinionDeedToAll(const std::shared_ptr<CScriptThing>& spActor, int eDeed);
	void EntityPostOpinionDeedToRecipient(const std::shared_ptr<CScriptThing>& spActor, int eDeed, const std::shared_ptr<CScriptThing>& spRecipient);
	void EntityPostOpinionDeedToRecipientVillage(const std::shared_ptr<CScriptThing>& spActor, int eDeed, const std::shared_ptr<CScriptThing>& spVillage);
	void RemoveOpinionDeedStillSearchingForWitnesses(const std::shared_ptr<CScriptThing>& spActor, int deedID);
	void EntitySetAsAwareOfThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	void EntitySetSoundRadius(const std::shared_ptr<CScriptThing>& spThing, float radius);
	void EntitySetSmellRadius(const std::shared_ptr<CScriptThing>& spThing, float radius);
	void EntitySetSightRadius(const std::shared_ptr<CScriptThing>& spThing, float radius);
	void EntitySetExtendedSightRadius(const std::shared_ptr<CScriptThing>& spThing, float radius);
	void EntitySetGiveUpChaseRadius(const std::shared_ptr<CScriptThing>& spThing, float radius);
	void SetTimeOfDay(float time);
	void SetTimeAsStopped(bool bIsStopped);
	void FastForwardTimeTo(float time, float duration);
	void TransitionToTheme(const std::string& themeName, float duration);
	void ResetToDefaultTheme(float duration);
	void TransitionToThemeAllInternals(const std::string& themeName, float duration);
	void ResetToDefaultThemeAllInternals(float duration);
	void TransitionToThemeExternals(const std::string& themeName, float duration);
	void ResetToDefaultThemeExternals(float duration);
	void SetEnvironmentThemeWeightAllChannels(const std::string& themeName, float weight);
	void SetEnvironmentThemeWeightAllInternals(const std::string& themeName, float weight);
	void SetEnvironmentThemeWeightExternals(const std::string& themeName, float weight);
	void SetSoundThemesAsEnabledForRegion(const std::string& regionName, bool bIsEnabled);
	void SetAllSoundsAsMuted(bool bIsMuted);
	void* RadialBlurFadeTo_NoPos(float f1, float f2, float f3, float f4, float f5, float f6, float f7);
	void* RadialBlurFadeTo_WithPos(float f1, sol::table v1, float f2, sol::table v2, float f3, float f4, float f5);
	void RadialBlurFadeOut(float duration, void* pBlur);
	void CancelRadialBlurFade();
	void RadialBlurSetCenterWorldPos(void* pBlur, sol::table pos);
	void* DisplacementMonochromeEffectColourFadeTo(float duration, sol::table color);
	void DisplacementMonochromeEffectColourFadeOut(float duration, void* pEffect);
	void* ScreenFilterFadeTo(float f1, float f2, float f3, float f4, float f5, sol::table color);
	void ScreenFilterFadeOut(float duration, void* pFilter);
	void SetThingAndCarriedItemsNotAffectedByScreenFilter(const std::shared_ptr<CScriptThing>& spThing, void* pFilter);
	void UnSetThingAndCarriedItemsNotAffectedByScreenFilter(const std::shared_ptr<CScriptThing>& spThing);
	void ApplyScriptBrush(const std::string& brushName);
	void EnableDecals(bool bIsEnabled);
	void EnableSounds(bool bIsEnabled);
	void StopSound(unsigned int soundID);
	void CacheMusicSet(int eType);
	void EnableDangerMusic(bool bIsEnabled);
	void StartCountdownTimer(float time);
	void AutoSaveCheckPoint();
	void AutoSaveQuestStart();
	void AutoSave();
	void SetSavingAsEnabled(bool bIsEnabled);
	void SetSaveGameMarkerPos(sol::table pos);
	void ResetToFrontEnd();
	void SetGuildSealRecallLocation(sol::table pos, float angle);
	void SetReadableObjectText(const std::shared_ptr<CScriptThing>& spThing, const std::string& text);
	void SetReadableObjectTextTag(const std::shared_ptr<CScriptThing>& spThing, const std::string& textTag);
	void RemoveRumourCategory(const std::string& categoryName);
	void SetCategoryActivity(const std::string& categoryName, bool bIsActive);
	void AddGossipVillage(const std::string& categoryName, const std::string& villageName);
	void SetIsGossipForPlayer_ByObject(const std::string& categoryName, bool bIsForPlayer);
	void SetIsGossipForPlayer_ByName(const std::string& categoryName, bool bIsForPlayer);
	void StartSneaking();
	void SetUseableByHero(const std::shared_ptr<CScriptThing>& spThing, bool bIsUseable);
	void SetOwnedByHero(const std::shared_ptr<CScriptThing>& spThing, bool bIsOwned);
	void SetTavernTableAvailableForUse(const std::shared_ptr<CScriptThing>& spTable, bool bIsAvailable);
	void SetIsThingTurncoatable(const std::shared_ptr<CScriptThing>& spThing, bool bIsTurncoatable);
	void SetIsThingForcePushable(const std::shared_ptr<CScriptThing>& spThing, bool bIsPushable);
	void SetIsThingLightningable(const std::shared_ptr<CScriptThing>& spThing, bool bIsLightningable);
	void SetIsThingEpicSpellable(const std::shared_ptr<CScriptThing>& spThing, bool bIsSpellable);
	void AddCreatureScriptedMode(const std::shared_ptr<CScriptThing>& spCreature, const std::string& mode);
	void RemoveCreatureScriptedMode(const std::shared_ptr<CScriptThing>& spCreature);
	void ForceShipsVisible();
	void SetBedAvailability(const std::shared_ptr<CScriptThing>& spBed, bool bIsAvailable);
	void RepopulateVillage(const std::shared_ptr<CScriptThing>& spVillage);
	void SmashAllWindowsWithinRadiusOfPoint(sol::table pos, float radius);
	void SetThankingPhrase(const std::shared_ptr<CScriptThing>& spThing, unsigned int phraseID);
	void EntityPlayObjectAnimation(const std::shared_ptr<CScriptThing>& spThing, const std::string& animName, sol::optional<bool> bUnknown);
	void ResetThankingPhrase(const std::shared_ptr<CScriptThing>& spThing);
	void SetIgnoringPhrase(const std::shared_ptr<CScriptThing>& spThing, unsigned int phraseID);
	void ResetIgnoringPhrase(const std::shared_ptr<CScriptThing>& spThing);
	void SetWanderCentrePoint(const std::shared_ptr<CScriptThing>& spThing, sol::table pos);
	void ResetWanderCentrePoint(const std::shared_ptr<CScriptThing>& spThing);
	void SetWanderMinDistance(const std::shared_ptr<CScriptThing>& spThing, float distance);
	void ResetWanderMinDistance(const std::shared_ptr<CScriptThing>& spThing);
	void SetWanderMaxDistance(const std::shared_ptr<CScriptThing>& spThing, float distance);
	void ResetWanderMaxDistance(const std::shared_ptr<CScriptThing>& spThing);
	void SetGossipCounter(const std::shared_ptr<CScriptThing>& spThing, int count);
	void ResetGossipCounter(const std::shared_ptr<CScriptThing>& spThing);
	void SetMaxGossipPhrase(const std::shared_ptr<CScriptThing>& spThing, int max);
	void ResetMaxGossipPhrase(const std::shared_ptr<CScriptThing>& spThing);
	void SetWarningPhrase(const std::shared_ptr<CScriptThing>& spThing, unsigned int phraseID);
	void ResetWarningPhrase(const std::shared_ptr<CScriptThing>& spThing);
	void SetGossipVillages(const std::string& category, const std::string& village, int index);
	void ClearGossipVillages(const std::string& category);
	void RemoveGossipVillages(const std::string& category);
	void AddGossipVillages(const std::string& category);
	void AddGossipVillages(const std::string& category, const std::string& village);
	void SetGossipFactions(const std::string& category, const std::string& faction, int index);
	void ClearGossipFactions(const std::string& category);
	void RemoveGossipFactions(const std::string& category);
	void AddGossipFactions(const std::string& category);
	void AddGossipFactions(const std::string& category, const std::string& faction);
	void SetTrapAsActive(const std::shared_ptr<CScriptThing>& spTrap, bool bIsActive);
	void SetCreatureCreationDelayFrames(int frames);
	void ResetCreatureCreationDelayFrames();
	void RemoveBoastMessage();
	void RemoveAllCutSceneSkippedMessages();
	void RespawnHero(bool bUnknown);
	void CancelHeroTeleportEffects();
	void EntityFollowThing(const std::shared_ptr<CScriptThing>& spFollower, const std::shared_ptr<CScriptThing>& spTarget, float distance, bool bUnknown);
	void EntityStopFollowing(const std::shared_ptr<CScriptThing>& spFollower);
	void SetCreatureBrain(const std::shared_ptr<CScriptThing>& spCreature, const std::string& brainName);
	bool NewScriptFrame();
	bool NewScriptFrame(CScriptThing* pMe);
	bool IsRegionLoaded(const std::string& regionName);
	bool IsDistanceBetweenThingsUnder(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2, float distance);
	bool IsLevelLoaded(const std::string& levelName);
	bool IsObjectInHeroPossession(const std::string& objectDefName);
	bool GiveHeroTutorial(int category);
	bool GetHeroHasMarried();
	bool GetHeroHasMurderedWife();
	bool GetFaceHeroForAction(const std::shared_ptr<CScriptThing>& spThing);
	bool GetAttackHeroOnSight(const std::shared_ptr<CScriptThing>& spThing);
	bool GetStealStealableItems(const std::shared_ptr<CScriptThing>& spThing);
	bool GetRecoverStealableItems(const std::shared_ptr<CScriptThing>& spThing);
	bool GetTakeStealableItemToRandomDestination(const std::shared_ptr<CScriptThing>& spThing);
	bool GetKillSelfAndStealableItemAfterReachingDestination(const std::shared_ptr<CScriptThing>& spThing);
	bool GetAllowedToFollow(const std::shared_ptr<CScriptThing>& spThing);
	bool GetDisableHeadLooking(const std::shared_ptr<CScriptThing>& spThing);
	bool GetIsPushableByHero(const std::shared_ptr<CScriptThing>& spThing);
	bool GetLookForFiniteTime(const std::shared_ptr<CScriptThing>& spThing);
	bool GetAvoidRegionExits(const std::shared_ptr<CScriptThing>& spThing);
	bool GetPlayerUsingMeleeDummies();
	bool GetPlayerUsingRangedDummies();
	bool GetPlayerUsingWillDummies();
	bool GetCheapHeadLooking();
	bool GetQuitTavernGame();
	bool GetPrizeTavernTable();
	bool GetBettingActive();
	bool GetBettingAccept();
	bool GetCountBetMoneyDown();
	bool GetSpotTheAdditionBeaten();
	bool GetBoastingEnabled();
	bool GetStateBool(const std::string& key);
	bool GetGlobalBool(const std::string& key);
	bool PersistTransferBool(void* pContext, const std::string& name, bool value);
	bool IsConversationActive(int conversationID);
	bool MsgIsLevelLoaded(const std::string& levelName);
	bool MsgIsLevelUnloaded(const std::string& levelName);
	bool MsgOnQuestCompleted(const std::string& questName);
	bool MsgOnQuestFailed(const std::string& questName);
	bool IsHeroAllowedHenchmenInCurrentRegion();
	bool IsHeroAllowedHenchmenInRegion(const std::string& regionName);
	bool MsgOnHeroUsedGuildSeal();
	bool MsgOnGameSavedManually();
	bool MsgOnHeroFiredRangedWeapon();
	bool IsSafeToDisplayGameInfo();
	bool DisplayTutorial(int category);
	bool IsTutorialSystemEnabled();
	bool GiveHeroItemsFromContainer(const std::shared_ptr<CScriptThing>& spContainerThing, bool bShowUI);
	bool IsReportedOrUnreportedCrimeKnown(const std::shared_ptr<CScriptThing>& spVillage);
	bool IsPlayerZTargetingThing(const std::shared_ptr<CScriptThing>& spThing);
	bool IsPlayerCreatureBlocking();
	bool IsHeroRenownLevelFull();
	bool IsPlayerCreatureFlourishEnabled();
	bool IsHeroHandLampLit();
	bool IsWearingClothingItem(const std::shared_ptr<CScriptThing>& spThing, const std::string& clothingDefName);
	bool IsHeroNaked();
	bool IsWearingHairstyle(const std::shared_ptr<CScriptThing>& spThing, const std::string& hairstyleDefName);
	bool IsPlayerCarryingItemOfType(const std::string& defName);
	bool IsPlayerWieldingWeapon();
	bool IsEntityWieldingWeapon(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityWieldingMeleeWeapon(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityWieldingRangedWeapon(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityMarriedToHero(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityMarriable(const std::shared_ptr<CScriptThing>& spThing);
	bool HeroHasExpression(const std::string& pExpressionName);
	bool IsHeroPerformingExpression(const std::string& pExpressionName);
	bool IsHeroOnQuest();
	bool IsQuestActive(const std::string& questName);
	bool IsQuestRegistered(const std::string& questName);
	bool IsQuestCompleted(const std::string& questName);
	bool IsQuestFailed(const std::string& questName);
	bool IsToFailQuestOnDeath();
	bool IsEntityPickPocketable(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityPickLockable(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityStealable(const std::shared_ptr<CScriptThing>& spThing);
	bool IsScreenFadingOut();
	bool IsCameraPosOnScreen(sol::table pos);
	bool IsChestOpen(const std::shared_ptr<CScriptThing>& spChest);
	bool OpenChest(const std::shared_ptr<CScriptThing>& spChest, sol::optional<bool> bUnknown);
	bool IsSleepingTime(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityInLimbo(const std::shared_ptr<CScriptThing>& spThing);
	bool EntityCastForcePush(const std::shared_ptr<CScriptThing>& spCaster, sol::optional<bool> bUnknown);
	bool EntityWillTeleportToArea(const std::shared_ptr<CScriptThing>& spThing, sol::table pos, float f1, float f2);
	bool CreatureGeneratorIsDepleted(const std::shared_ptr<CScriptThing>& spGenerator);
	bool CreatureGeneratorIsDestroyed(const std::shared_ptr<CScriptThing>& spGenerator);
	bool CreatureGeneratorAreAllCreaturesAlive(const std::shared_ptr<CScriptThing>& spGenerator);
	bool IsCreatureGenerationEnabledForRegion(const std::string& regionName);
	bool IsCreatureFlying(const std::shared_ptr<CScriptThing>& spCreature);
	bool IsTeleporterActive(const std::shared_ptr<CScriptThing>& spTeleporter);
	bool IsTeleportingActive();
	bool IsHeroSleepingEnabled();
	bool IsBoastTaken(int boastID, const std::string& questName);
	bool IsCameraInScriptedMode();
	bool MsgOnLeavingExperienceSpendingScreen();
	bool MsgIsBoastMade(int boastID);
	bool AreEntitiesEnemies(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	bool IsThingOnFire(const std::shared_ptr<CScriptThing>& spThing);
	bool IsDiggingSpotEnabled(const std::shared_ptr<CScriptThing>& spSpot);
	bool IsDiggingSpotHidden(const std::shared_ptr<CScriptThing>& spSpot);
	bool CheckForCameraMessage(const std::string& message);
	bool IsDeedWitnessed(int deedID);
	bool CanThingBe_Seen_ByOtherThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	bool CanThingBe_NearlySeen_ByOtherThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	bool CanThingBe_Smelled_ByOtherThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	bool CanThingBe_Heard_ByOtherThing(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	bool IsThingAwareOfOtherThingInAnyWay(const std::shared_ptr<CScriptThing>& spThing1, const std::shared_ptr<CScriptThing>& spThing2);
	bool IsRadialBlurFadeActive();
	bool IsGiftRomantic(const std::string& giftName);
	bool IsGiftFriendly(const std::string& giftName);
	bool IsGiftOffensive(const std::string& giftName);
	bool IsThingABed(const std::shared_ptr<CScriptThing>& spThing);
	bool IsThingAChest(const std::shared_ptr<CScriptThing>& spThing);
	bool IsThingADoor(const std::shared_ptr<CScriptThing>& spThing);
	bool IsThingSmashable(const std::shared_ptr<CScriptThing>& spThing);
	bool IsThingSearchable(const std::shared_ptr<CScriptThing>& spThing);
	bool IsSoundPlaying(unsigned int soundID);
	bool IsDangerMusicEnabled();
	bool IsSavingEnabled();
	bool IsHeroInTavernGame();
	bool IsThingTurncoated(const std::shared_ptr<CScriptThing>& spThing);
	bool MsgIsGameInfoClickedPast();
	bool MsgIsTutorialClickedPast();
	bool MsgIsActionModeButtonPressed();
	bool MsgIsCutSceneSkipped();
	bool GetHeroHasCurrentMarriage();
	bool GetHeroHasDivorcedMarriage();
	bool GetHeroHasChildren();
	bool IsHeroChild();
	bool MsgOnChestOpeningCancelled();
	bool IsEntityFollowingHero(const std::shared_ptr<CScriptThing>& spThing);
	bool IsEntityAbleToAttack(const std::shared_ptr<CScriptThing>& spThing);
	bool IsInCutscene();
	bool IsTimeOfDayBetween(int startTime, int endTime);
	bool ManuallyTriggerTrap(const std::shared_ptr<CScriptThing>& spTrap);
	bool ManuallyResetTrap(const std::shared_ptr<CScriptThing>& spTrap);
	int EntityGetStockItemPrice(CScriptThing* pThing);
	int GetWorldFrame();
	int GiveHeroYesNoQuestion(const std::string& question, const std::string& button1, const std::string& button2, const std::string& button3);
	int RegisterTimer();
	int GetTimer(int timerId);
	int EntityGetBossPhase(CScriptThing* pThing);
	int GetHeroGold();
	int GetHeroRenownLevel();
	int GetHeroTitle();
	int AddQuestInfoTimer(int timerId, const std::string& text, float scale);
	int AddQuestInfoCounterList(const std::string& text, int count, float scale);
	int AddQuestInfoTickByAction(int gameAction, bool bState, float scale);
	int AddQuestInfoTickByText(const std::string& text, bool bState, float scale);
	int GetHeroWillEnergy();
	int GetHeroWillEnergyMax();
	int GetHeroWillEnergyPercentage();
	int GetHeroRoughExperienceLevel();
	int GetHeroExperienceAvailableToSpend();
	int GetHeroMoralityCategory();
	int GetPlayerCreatureCombatMultiplier();
	int GetPlayerCreatureCombatMultiplierRunningNumHits();
	int GetActiveGossipCategoriesSize();
	int GetScriptingStateGroup(const std::shared_ptr<CScriptThing>& spThing);
	int GetTimeToSpendHarassingHero(const std::shared_ptr<CScriptThing>& spThing);
	int GetActionFrequency(const std::shared_ptr<CScriptThing>& spThing);
	int GetBettingAmount();
	int GetIsGossipForPlayerSize();
	int GetGossipSize(const std::string& category);
	int GetStateInt(const std::string& key);
	int GetGlobalInt(const std::string& key);
	int PersistTransferInt(void* pContext, const std::string& name, int value);
	int StartAmbientConversation(const std::shared_ptr<CScriptThing>& spSpeaker, const std::shared_ptr<CScriptThing>& spListener,
		sol::optional<bool> soundIn2D, sol::optional<bool> playDuringCutscene);
	int AddQuestInfoBar(float current, float max, sol::table color1, sol::table color2, const std::string& texture, const std::string& text, float scale);
	int AddQuestInfoBarHealth(const std::shared_ptr<CScriptThing>& spThing, sol::table color, const std::string& texture, float scale);
	int AddQuestInfoCounter(const std::string& text, int count, float scale);
	int GetHeroStrengthLevel();
	int GetHeroSkillLevel();
	int GetHeroWillLevel();
	int GetHeroStatLevel(int statType);
	int GetHeroStatMax(int statType);
	int GetNumberOfItemsOfTypeInInventory(const std::string& defName);
	int GetNumberOfTimesHeroHasHadSex();
	int EntityGetSex(const std::shared_ptr<CScriptThing>& spThing);
	int CreatureGeneratorGetNumGeneratedCreatures(const std::shared_ptr<CScriptThing>& spGenerator);
	int GetNextInOpinionAttitudeGraph(int eCurrent);
	int EntityGetOpinionAttitudeToPlayer(const std::shared_ptr<CScriptThing>& spThing);
	int EntityPostOpinionDeedKeepSearchingForWitnesses(const std::shared_ptr<CScriptThing>& spActor, int eDeed, const std::shared_ptr<CScriptThing>& spRecipient);
	int GetTimeOfDay();
	int GetDayOfWeek();
	int GetDayCount();
	int GetConstantFPS();
	int GetBestScoreBlackjack();
	int GetBestScoreCoinGolfOakVale();
	int GetBestScoreCoinGolfSnowSpire();
	int GetBestScoreShoveHaPenny();
	int GetNumHousesOwned();
	int GetStealDuration(const std::shared_ptr<CScriptThing>& spThing);
	int GetGossipCounter(const std::shared_ptr<CScriptThing>& spThing);
	int GetMaxGossipPhrase(const std::shared_ptr<CScriptThing>& spThing);
	int GetGossipVillagesSize(const std::string& category);
	int GetGossipFactionsSize(const std::string& category);
	int MsgIsQuestionAnsweredYesOrNo();
	unsigned int GetThankingPhrase(const std::shared_ptr<CScriptThing>& spThing);
	unsigned int PlayCriteriaSoundOnThing(const std::shared_ptr<CScriptThing>& spThing, const std::string& soundName);
	unsigned int PersistTransferUInt(void* pContext, const std::string& name, unsigned int value);
	unsigned int GetBeerRequestPhrase(const std::shared_ptr<CScriptThing>& spThing);
	unsigned int EntityGetAppearanceSeed(const std::shared_ptr<CScriptThing>& spThing);
	unsigned int GetIgnoringPhrase(const std::shared_ptr<CScriptThing>& spThing);
	unsigned int GetWarningPhrase(const std::shared_ptr<CScriptThing>& spThing);
	unsigned int PlaySoundOnThing(std::shared_ptr<CScriptThing> pThing, const std::string& soundName);
	unsigned int Play2DSound(const std::string& soundName);
	unsigned int PlaySoundAtPos(sol::table position, const std::string& soundName);
	float GetHeroAge();
	float GetHealth(CScriptThing* pThing);
	float GetHeroFatness();
	float GetActionFrequencyVariation(const std::shared_ptr<CScriptThing>& spThing);
	float GetMaxHeroReactionDistance(const std::shared_ptr<CScriptThing>& spThing);
	float GetFollowDistance(const std::shared_ptr<CScriptThing>& spThing);
	float GetCombatNearbyEnemyFleeingBreakOffRange(const std::shared_ptr<CScriptThing>& spThing);
	float GetCombatNearbyBreakOffRange(const std::shared_ptr<CScriptThing>& spThing);
	float GetTargetingDistanceOffset(const std::shared_ptr<CScriptThing>& spThing);
	float PersistTransferFloat(void* pContext, const std::string& name, float value);
	float GetGlobalTargetingDistanceOffset();
	float GetTradingPriceMult();
	float GetHeroMorality();
	float GetDistanceHeroCanBeHeardFrom();
	float GetHeroScariness();
	float GetHeroAttractiveness();
	float GetHeroWillEnergyLevel();
	float GetWaterHeightAtPosition(sol::table position);
	float GetHeroHealthMax();
	float GetHeroHealthPercentage();
	float GetGameAngleXY();
	float EntityGetOpinionOfPlayer(const std::shared_ptr<CScriptThing>& spThing, int eOpinion);
	float EntityGetHearingRadius(const std::shared_ptr<CScriptThing>& spThing);
	float GetCountdownTimer();
	float GetGuildSealRecallAngleXY();
	float GetBestTimePairs();
	float GetBestTimeSorting();
	float GetBestTimeGuessTheAddition();
	float GetWanderMinDistance(const std::shared_ptr<CScriptThing>& spThing);
	float GetWanderMaxDistance(const std::shared_ptr<CScriptThing>& spThing);
	float GetHeroHealth();
	sol::object MsgOnHeroCastSpell(sol::this_state s);
	sol::object GetMasterGameState(const std::string& flagName, sol::this_state s);
	sol::object GetActiveGossipCategories(sol::this_state s);
	sol::object GetActiveGossipCategories(const std::string& category, sol::this_state s);
	sol::object GetIsGossipForPlayer(sol::this_state s);
	sol::object GetIsGossipForPlayer(const std::string& category, sol::this_state s);
	sol::object GetGossip(const std::string& category, sol::this_state s);
	sol::object MsgOnQuestAccepted(sol::this_state s);
	sol::object MsgOnHeroPickedPocket(sol::this_state s);
	sol::object MsgOnHeroPickedLock(sol::this_state s);
	sol::object MsgOnFishingGameFinished(sol::this_state s);
	sol::object MsgOnTavernGameFinished(sol::this_state s);
	sol::object MsgOnHeroRewardedWithItemsFrom(sol::this_state s);
	sol::object MsgOnHeroHairTypeChanged(int area, sol::this_state s);
	sol::object MsgOnHeroUsedTeleporter(sol::this_state s);
	sol::object MsgOnHeroSlept(sol::this_state s);
	sol::object GetPreviouslyWieldedMeleeWeaponName(sol::this_state s);
	sol::object GetPreviouslyWieldedRangedWeaponName(sol::this_state s);
	sol::object GetNumberOfKeysNeededToUnlockChest(const std::shared_ptr<CScriptThing>& spChest, sol::this_state s);
	sol::object MsgOnExpressionPerformed(sol::this_state s);
	sol::object IsQuestStartScreenActive(sol::this_state s);
	sol::object MsgOnLeavingQuestStartScreen(sol::this_state s);
	sol::object MsgOnFeatAccepted(sol::this_state s);
	sol::object IsPlayerCreatureReadyToFireProjectileWeapon(sol::this_state s);
	sol::object EntityGetShotStrikePos(const std::shared_ptr<CScriptThing>& spThing, sol::this_state s);
	sol::object GetGossipVillages(const std::string& category, sol::this_state s);
	sol::object GetGossipFactions(const std::string& category, sol::this_state s);
	std::shared_ptr<CScriptThing> GetHero();
	std::shared_ptr<CScriptThing> GetThingWithScriptName(const std::string& scriptName);
	std::shared_ptr<CScriptThing> GetThingWithUID(const std::string& uid_str);
	std::shared_ptr<CScriptThing> GetThingWithScriptNameAtRegion(const std::string& scriptName, const std::string& regionName);
	std::shared_ptr<CScriptThing> GetNearestWithDefName(const std::shared_ptr<CScriptThing>& spRelativeTo, const std::string& defName);
	std::shared_ptr<CScriptThing> GetHeroTargetedThing();
	std::shared_ptr<CScriptThing> GetNearestWithScriptName(const std::shared_ptr<CScriptThing>& spRelativeTo, const std::string& scriptName);
	std::shared_ptr<CScriptThing> GetFurthestWithScriptName(const std::shared_ptr<CScriptThing>& spRelativeTo, const std::string& scriptName);
	std::shared_ptr<CScriptThing> GetFurthestWithDefName(const std::shared_ptr<CScriptThing>& spRelativeTo, const std::string& defName);
	std::shared_ptr<CScriptThing> CreateLight(sol::table position, sol::table color, const std::string& scriptName, float innerRadius, float outerRadius, sol::optional<float> flicker);
	std::shared_ptr<CScriptThing> CreateObjectOnEntity(const std::string& defName, const std::shared_ptr<CScriptThing>& spOnThing, const std::string& scriptName);
	std::shared_ptr<CScriptThing> CreateCreatureOnEntity(const std::string& defName, const std::shared_ptr<CScriptThing>& spOnThing, const std::string& scriptName);
	std::shared_ptr<CScriptThing> TurnCreatureInto(const std::shared_ptr<CScriptThing>& spTarget, const std::string& newDefName);
	std::shared_ptr<CScriptThing> CreateCreature(const std::string& defName, sol::table position, const std::string& scriptName); 
	std::shared_ptr<CScriptThing> CreateObjectWithRotation(const std::string& defName, sol::table position, float rotation, const std::string& scriptName);
	std::shared_ptr<CScriptThing> CreateObject(const std::string& defName, sol::table position, const std::string& scriptName);
	std::shared_ptr<CScriptThing> CreateCreatureNearby(const std::string& defName, sol::table position, float radius, const std::string& scriptName);
	std::shared_ptr<CScriptThing> CreateEffectAtPos(const std::string& effectName, sol::table position,sol::optional<float> angle, sol::optional<bool> independent, sol::optional<bool> alwaysUpdate);
	std::shared_ptr<CScriptThing> CreateEffectOnThing(const std::string& effectName, CScriptThing* pTarget, const std::string& boneName,sol::optional<bool> independent, sol::optional<bool> alwaysUpdate);
	std::shared_ptr<CScriptThing> CreateExperienceOrb(sol::table position, int amount);
	std::shared_ptr<CScriptThing> CreateExplosion(const std::string& defName, sol::table position, sol::table direction, const std::string& scriptName);
	std::shared_ptr<CScriptThing> CreatePhysicalBarrier(float size, sol::table position, sol::table direction, const std::string& scriptName);
	std::shared_ptr<CScriptThing> CreateRumble(sol::table position, float f1, float f2, const std::string& scriptName);
	std::shared_ptr<CScriptThing> TryToRespawnDefNamed(const std::shared_ptr<CScriptThing>& spThing, const std::string& defName, sol::table pos);
	std::shared_ptr<CScriptThing> GetMostRecentValidUsedTarget();
	std::shared_ptr<CScriptThing> EntityGetStandingOnThing(const std::shared_ptr<CScriptThing>& spThing);
	std::shared_ptr<CScriptThing> EntityGetStandingInsideBuilding(const std::shared_ptr<CScriptThing>& spThing);
	std::shared_ptr<CScriptThing> GetNearestEnabledDiggingSpot(const std::shared_ptr<CScriptThing>& spRelativeTo);
	std::shared_ptr<CScriptThing> SetResidency(const std::shared_ptr<CScriptThing>& spThing, bool bIsResident);
	std::shared_ptr<CScriptThing> GetRandomThingWithScriptName(const std::string& scriptName);
	std::shared_ptr<CScriptThing> EntityGetThingInPrimarySlot(const std::shared_ptr<CScriptThing>& spThing);
	sol::table GetItemDefNamesFromContainer(const std::shared_ptr<CScriptThing>& spContainer, sol::this_state s);
	sol::table GetAllThingsWithDefName(const std::string& defName, sol::this_state s);
	sol::table GetAllThingsWithScriptName(const std::string& scriptName, sol::this_state s);
	sol::table GetFollowingEntityList(const std::shared_ptr<CScriptThing>& spTarget, sol::this_state s);
	sol::table GetHeroSummonedCreaturesList(sol::this_state s);
	sol::table GetPerceivingHeroEntityList(sol::this_state s);
	sol::table GetAllCreaturesExcludingHero(sol::this_state s);
	sol::table GetAllThingsWithDefNameByDistanceFrom(const std::shared_ptr<CScriptThing>& spRelativeTo, const std::string& defName, sol::this_state s);
	sol::table GetAllCreaturesInAreaWithScriptName(const std::string& scriptName, sol::table position, float radius, sol::this_state s);
	sol::table GetWanderCentrePoint(const std::shared_ptr<CScriptThing>& spThing, sol::this_state s);
	sol::table DebugGetAllTextEntriesForTargetedThing(sol::this_state s);
	sol::table GetThingDebugInfo(CScriptThing* pThing, sol::this_state s);
	sol::table MsgOnBoastsMade(sol::this_state s);
	sol::table GetSleepingPositionAndOrientationFromBed(const std::shared_ptr<CScriptThing>& spBed, const std::shared_ptr<CScriptThing>& spSleeper, sol::this_state s);
	sol::table GetAllActiveQuestInfo(sol::this_state s);
	sol::table GetGuildSealRecallPos(sol::this_state s);
	std::string GetActiveQuestName();
	std::string GetAction(const std::shared_ptr<CScriptThing>& spThing);
	std::string GetTargetName(const std::shared_ptr<CScriptThing>& spThing);
	std::string GetTableName(const std::shared_ptr<CScriptThing>& spThing);
	std::string GetSeatName(const std::shared_ptr<CScriptThing>& spThing);
	std::string GetStateString(const std::string& key);
	std::string GetGossip(const std::string& category, int index);
	std::string GetGlobalString(const std::string& key);
	std::string PersistTransferString(void* pContext, const std::string& name, const std::string& value);
	std::string GetRegionName();
	std::string GetExclusiveQuestScriptName();
	std::string GetDeathRecoveryMarkerName();
	std::string GetMostRecentValidUsedTargetName();
	std::string GetOpinionAttitudeAsString(int eAttitude);
	std::string EntityGetOpinionAttitudeToPlayerAsString(const std::shared_ptr<CScriptThing>& spThing);
	std::string GetGossipVillages(const std::string& category, int index);
	std::string GetGossipFactions(const std::string& category, int index);