-- MyDeliveryQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyDeliveryQuest: Init phase started.")
    Quest:AddQuestRegion("MyDeliveryQuest", "Oakvale")
    Quest:AddQuestRegion("MyDeliveryQuest", "Bowerstone")
    Quest:AddQuestRegion("MyDeliveryQuest", "Knothole")
    Quest:SetQuestWorldMapOffset("MyDeliveryQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyDeliveryQuest", false, false)
    Quest:SetQuestCardObjective("MyDeliveryQuest", "Make deliveries to three towns", "Oakvale", "")
    Quest:SetQuestGoldReward("MyDeliveryQuest", 2000)
    Quest:SetQuestRenownReward("MyDeliveryQuest", 200)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateBool("Delivered Oakvale", false)
    Quest:SetStateBool("Delivered Bowerstone", false)
    Quest:SetStateBool("Delivered Knothole", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyDeliveryQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("DeliveryManager", "MyDeliveryQuest/Entities/DeliveryManager")
    Quest:AddEntityBinding("DeliveryOakvale", "MyDeliveryQuest/Entities/DeliveryOakvale")
    Quest:AddEntityBinding("DeliveryBowerstone", "MyDeliveryQuest/Entities/DeliveryBowerstone")
    Quest:AddEntityBinding("DeliveryKnothole", "MyDeliveryQuest/Entities/DeliveryKnothole")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferBool(context, "Delivered Oakvale")
    Quest:PersistTransferBool(context, "Delivered Bowerstone")
    Quest:PersistTransferBool(context, "Delivered Knothole")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("MyDeliveryQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_DeliveryManager = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_DeliveryManager = nil
    if marker_DeliveryManager ~= nil and marker_DeliveryManager.GetPos ~= nil then
        local ok, result = pcall(function() return marker_DeliveryManager:GetPos() end)
        if ok then
            pos_DeliveryManager = result
        end
    end
    if pos_DeliveryManager == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_DeliveryManager = result
            end
        end
    end
    if pos_DeliveryManager ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_DeliveryManager, "DeliveryManager") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for DeliveryManager")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_DeliveryOakvale = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_DeliveryOakvale = nil
    if marker_DeliveryOakvale ~= nil and marker_DeliveryOakvale.GetPos ~= nil then
        local ok, result = pcall(function() return marker_DeliveryOakvale:GetPos() end)
        if ok then
            pos_DeliveryOakvale = result
        end
    end
    if pos_DeliveryOakvale == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_DeliveryOakvale = result
            end
        end
    end
    if pos_DeliveryOakvale ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_DeliveryOakvale, "DeliveryOakvale") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for DeliveryOakvale")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_DeliveryBowerstone = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_DeliveryBowerstone = nil
    if marker_DeliveryBowerstone ~= nil and marker_DeliveryBowerstone.GetPos ~= nil then
        local ok, result = pcall(function() return marker_DeliveryBowerstone:GetPos() end)
        if ok then
            pos_DeliveryBowerstone = result
        end
    end
    if pos_DeliveryBowerstone == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_DeliveryBowerstone = result
            end
        end
    end
    if pos_DeliveryBowerstone ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_DeliveryBowerstone, "DeliveryBowerstone") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for DeliveryBowerstone")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_DeliveryKnothole = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_DeliveryKnothole = nil
    if marker_DeliveryKnothole ~= nil and marker_DeliveryKnothole.GetPos ~= nil then
        local ok, result = pcall(function() return marker_DeliveryKnothole:GetPos() end)
        if ok then
            pos_DeliveryKnothole = result
        end
    end
    if pos_DeliveryKnothole == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_DeliveryKnothole = result
            end
        end
    end
    if pos_DeliveryKnothole ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_DeliveryKnothole, "DeliveryKnothole") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for DeliveryKnothole")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local DeliveryManager = Quest:GetThingWithScriptName("DeliveryManager")
    if DeliveryManager ~= nil then
        Quest:SetThingHasInformation(DeliveryManager, true)
        Quest:MiniMapAddMarker(DeliveryManager, "DeliveryManager")
    end
    local DeliveryOakvale = Quest:GetThingWithScriptName("DeliveryOakvale")
    if DeliveryOakvale ~= nil then
        Quest:SetThingHasInformation(DeliveryOakvale, true)
        Quest:MiniMapAddMarker(DeliveryOakvale, "DeliveryOakvale")
    end
    local DeliveryBowerstone = Quest:GetThingWithScriptName("DeliveryBowerstone")
    if DeliveryBowerstone ~= nil then
        Quest:SetThingHasInformation(DeliveryBowerstone, true)
        Quest:MiniMapAddMarker(DeliveryBowerstone, "DeliveryBowerstone")
    end
    local DeliveryKnothole = Quest:GetThingWithScriptName("DeliveryKnothole")
    if DeliveryKnothole ~= nil then
        Quest:SetThingHasInformation(DeliveryKnothole, true)
        Quest:MiniMapAddMarker(DeliveryKnothole, "DeliveryKnothole")
    end

    Quest:Log("MyDeliveryQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyDeliveryQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyDeliveryQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyDeliveryQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local DeliveryManager = Quest:GetThingWithScriptName("DeliveryManager")
            if DeliveryManager ~= nil and not DeliveryManager:IsNull() then
                Quest:ClearThingHasInformation(DeliveryManager)
                Quest:MiniMapRemoveMarker(DeliveryManager)
            end
            local DeliveryOakvale = Quest:GetThingWithScriptName("DeliveryOakvale")
            if DeliveryOakvale ~= nil and not DeliveryOakvale:IsNull() then
                Quest:ClearThingHasInformation(DeliveryOakvale)
                Quest:MiniMapRemoveMarker(DeliveryOakvale)
            end
            local DeliveryBowerstone = Quest:GetThingWithScriptName("DeliveryBowerstone")
            if DeliveryBowerstone ~= nil and not DeliveryBowerstone:IsNull() then
                Quest:ClearThingHasInformation(DeliveryBowerstone)
                Quest:MiniMapRemoveMarker(DeliveryBowerstone)
            end
            local DeliveryKnothole = Quest:GetThingWithScriptName("DeliveryKnothole")
            if DeliveryKnothole ~= nil and not DeliveryKnothole:IsNull() then
                Quest:ClearThingHasInformation(DeliveryKnothole)
                Quest:MiniMapRemoveMarker(DeliveryKnothole)
            end

            -- Give rewards
            Quest:GiveHeroGold(2000)
            Quest:GiveHeroExperience(400)
            Quest:GiveHeroRenownPoints(200)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyDeliveryQuest", true, false, false)
            Quest:DeactivateQuestLater("MyDeliveryQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

