-- RandomEntity.lua
-- Entity script for RandomQuest
-- Generated by Fable Quest Tool (FQT)

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("RandomEntity: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("RandomEntity: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:MsgIsUsedByHero() then
            -- Random choice (1 to 3)
            local randomChoice = math.random(1, 3)
            if randomChoice == 1 then
                Quest:ShowMessage("Choice 1", 1.0)
            elseif randomChoice == 2 then
                Quest:ShowMessage("Choice 2", 1.0)
            elseif randomChoice == 3 then
                Quest:ShowMessage("Choice 3", 1.0)
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
