-- ParallelEntity.lua
-- Entity script for ParallelQuest
-- Generated by Fable Quest Tool (FQT)

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("ParallelEntity: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("ParallelEntity: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:MsgIsUsedByHero() then
            -- Parallel execution is not supported in entity scripts; running sequentially
            Quest:ShowMessage("Left path", 1.0)
            Quest:ShowMessage("Right path", 1.0)
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
