-- WhileEntity.lua
-- Entity script for WhileQuest
-- Generated by Fable Quest Tool (FQT)

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("WhileEntity: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("WhileEntity: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:MsgIsUsedByHero() then
            while Me:IsAlive() do
                Quest:ShowMessage("While", 1.0)
            Quest:Pause(0)
            if Me:IsNull() then break end
            if not Quest:NewScriptFrame(Me) then break end
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
