-- TestEntity.lua
-- Entity script for SnapshotQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("TestEntity: Init called")
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("TestEntity: Main started")
    local hero = Quest:GetHero()

    -- Minimal behavior loop (add behavior nodes for triggers and actions)
    while true do
        -- Add trigger nodes in the visual editor to respond to hero interactions
        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
