-- BranchEntity.lua
-- Entity script for BranchQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("BranchEntity: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("BranchEntity: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:MsgIsUsedByHero() then
            if Quest:GetStateBool("HasItem") == true then
                Quest:ShowMessage("All good", 2.0)
            else
                Quest:ShowMessage("Not yet", 2.0)
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
