-- ManualChest.lua
-- Container entity script for ManualContainerQuest
-- Generated by FSE Quest Creator Pro

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("ManualChest: Init called")
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("ManualChest: Main started - waiting for hero interaction")

    -- Make container interactive
    Quest:EntitySetTargetable(Me, true)

    -- Wait for hero to interact with container
    while true do
        if Me:MsgIsUsedByHero() then
            Quest:Log("ManualChest: Hero opened container - giving rewards!")

            -- Give all items to hero
            Quest:GiveHeroObject("OBJECT_APPLE", 1)
            Quest:GiveHeroObject("OBJECT_CARROT", 1)

            -- Clear highlight
            Quest:ClearThingHasInformation(Me)

            -- Container opened - exit loop
            break
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
