-- EventEntity.lua
-- Entity script for EventQuest
-- Generated by Fable Quest Tool (FQT)

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("EventEntity: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("EventEntity: Main started")
    local hero = Quest:GetHero()

    -- Custom event functions
    -- Event: OnGift
    local function Event_OnGift()
        Quest:ShowMessage("Thanks", 2.0)
    end


    -- Main behavior loop
    while true do
        if Me:MsgIsUsedByHero() then
            Event_OnGift()
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
