-- RewardObject.lua
-- Entity script for ObjectRewardQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("RewardObject: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("RewardObject: Main started")
    local hero = Quest:GetHero()

    -- Auto-generated reward behavior for object
    -- This object gives rewards when interacted with by the hero

    local alreadyOpened = Quest:GetStateBool("RewardObject_opened")
    if alreadyOpened then
        Quest:Log("RewardObject: Already opened, skipping reward behavior")
        return
    end

    -- Make object interactive
    Quest:EntitySetTargetable(Me, true)
    Quest:SetThingHasInformation(Me, true)

    -- Wait for hero interaction
    while true do
        if Me:MsgIsUsedByHero() then
            Quest:Log("RewardObject: Hero interacted with object, giving rewards")

            Quest:GiveHeroGold(5)
            Quest:GiveHeroExperience(10)
            Quest:GiveHeroObject("OBJECT_APPLE", 1)
            Quest:GiveHeroObject("OBJECT_CARROT", 1)
            Quest:ShowMessage("Received: 5 gold, 10 XP, 2 item(s)", 3.0)

            Quest:SetStateBool("RewardObject_opened", true)

            -- Remove highlight since object was already used
            Quest:ClearThingHasInformation(Me)
            break
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
