-- ManualContainerQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("ManualContainerQuest: Init phase started.")
    Quest:AddQuestRegion("ManualContainerQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("ManualContainerQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "ManualContainerQuest", false, false)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("ManualContainerQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("ManualChest", "ManualContainerQuest/Entities/ManualChest")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("ManualContainerQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Container reward: Spawn and populate container
            Quest:Log("Attempting to spawn container...")
            local marker = Quest:GetThingWithScriptName("MK_REWARD")
            local containerPos
            if marker ~= nil then
                containerPos = marker:GetPos()
            else
                local hero = Quest:GetHero()
                containerPos = hero:GetPos()
            end
            Quest:Log("Creating container: OBJECT_CHEST at position...")
            local container = Quest:CreateObject("OBJECT_CHEST", containerPos, "ManualChest")
            Quest:Log("CreateObject returned: " .. tostring(container))
            if container ~= nil then
                Quest:Log("Container spawned successfully!")
                Quest:EntitySetTargetable(container, true)
                Quest:Log("Container set as targetable")
                -- Container uses entity script for multi-item rewards on manual open
                Quest:SetThingHasInformation(container, true)
            else
                Quest:Log("WARNING: Failed to spawn container!")
            end

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("ManualContainerQuest", true, false, false)
            Quest:DeactivateQuestLater("ManualContainerQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

