-- ThreadQuest.lua
-- Generated by Fable Quest Tool (FQT)

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("ThreadQuest: Init phase started.")
    Quest:AddQuestRegion("ThreadQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("ThreadQuest", 380, 340)
    Quest:SetStateBool("QuestCompleted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("ThreadQuest: Main() started.")

    -- Bind entity scripts
    Quest:AddEntityBinding("SpawnedNpc", "ThreadQuest/Entities/SpawnedNpc")
    Quest:FinalizeEntityBindings()

    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "ThreadQuest", false, false)

    -- Start quest threads
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
    Quest:CreateThread("WatcherThread", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    local QuestCompleted_value = Quest:GetStateBool("QuestCompleted")
    QuestCompleted_value = Quest:PersistTransferBool(context, "QuestCompleted", QuestCompleted_value)
    Quest:SetStateBool("QuestCompleted", QuestCompleted_value)
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("ThreadQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_SpawnedNpc = Quest:GetThingWithScriptName("MK_OVID_DAD")
    if marker_SpawnedNpc ~= nil then
        local pos_SpawnedNpc = marker_SpawnedNpc:GetPos()
        local SpawnedNpc = Quest:CreateCreature("CREATURE_VILLAGER_FARMER", pos_SpawnedNpc, "SpawnedNpc")
    else
        local hero = Quest:GetHero()
        local heroPos = hero:GetPos()
        local SpawnedNpc = Quest:CreateCreature("CREATURE_VILLAGER_FARMER", heroPos, "SpawnedNpc")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    Quest:Log("ThreadQuest: EntitySpawner completed.")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("ThreadQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("ThreadQuest", true, false, false)
            Quest:DeactivateQuestLater("ThreadQuest", 0)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

function WatcherThread(questObject)
    Quest = questObject
    -- Watch for conditions
    -- Thread entry point. Add quest logic here as needed.
    -- Exits when state 'StopThread' is true
    while true do
        if Quest:GetStateBool("StopThread") == true then break end
        Quest:Pause(0.25)
        if not Quest:NewScriptFrame() then break end
    end
end

