-- ExposedQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("ExposedQuest: Init phase started.")
    Quest:AddQuestRegion("ExposedQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("ExposedQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "ExposedQuest", false, false)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("ExposedQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("ExposedEntity", "ExposedQuest/Entities/ExposedEntity")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("ExposedQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_ExposedEntity = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_ExposedEntity = nil
    if marker_ExposedEntity ~= nil and marker_ExposedEntity.GetPos ~= nil then
        local ok, result = pcall(function() return marker_ExposedEntity:GetPos() end)
        if ok then
            pos_ExposedEntity = result
        end
    end
    if pos_ExposedEntity == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_ExposedEntity = result
            end
        end
    end
    if pos_ExposedEntity ~= nil then
        pcall(function() Quest:CreateCreature("", pos_ExposedEntity, "ExposedEntity") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for ExposedEntity")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    Quest:Log("ExposedQuest: EntitySpawner completed.")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("ExposedQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("ExposedQuest", true, false, false)
            Quest:DeactivateQuestLater("ExposedQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

