-- SnapshotQuest.lua
-- Generated by Fable Quest Tool (FQT)

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("SnapshotQuest: Init phase started.")
    Quest:AddQuestRegion("SnapshotQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("SnapshotQuest", 380, 340)
    Quest:SetStateBool("QuestCompleted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("SnapshotQuest: Main() started.")

    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "SnapshotQuest", false, false)
    Quest:SetQuestCardObjective("SnapshotQuest", "Do it", "Oakvale", "")

    Quest:SetQuestGoldReward("SnapshotQuest", 10)
    Quest:SetQuestRenownReward("SnapshotQuest", 5)

    -- Set quest info for start screen
    Quest:SetQuestInfoName("Snapshot Quest")
    Quest:SetQuestInfoText("Short quest\\n\\nRewards: 10 Gold, 5 Renown, 1 item(s)")
    -- Show quest start screen
    Quest:KickOffQuestStartScreen("SnapshotQuest", false, true)

    -- Start quest threads
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    local QuestCompleted_value = Quest:GetStateBool("QuestCompleted")
    QuestCompleted_value = Quest:PersistTransferBool(context, "QuestCompleted", QuestCompleted_value)
    Quest:SetStateBool("QuestCompleted", QuestCompleted_value)
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("SnapshotQuest: Quest completed, giving rewards...")

            -- Give rewards
            Quest:GiveHeroGold(10)
            Quest:GiveHeroRenownPoints(5)
            Quest:GiveHeroObject("OBJECT_APPLE", 1)
            Quest:Pause(0)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("SnapshotQuest", true, false, true)
            Quest:DeactivateQuestLater("SnapshotQuest", 0)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end
