-- PersistQuest.lua
-- Generated by Fable Quest Tool (FQT)

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("PersistQuest: Init phase started.")
    Quest:AddQuestRegion("PersistQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("PersistQuest", 380, 340)
    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("Flag", true)
    Quest:SetStateInt("Count", 2)
    Quest:SetStateString("Ratio", "1.25")
    Quest:SetStateString("Note", "Hi")
end

function Main(questObject)
    Quest = questObject
    Quest:Log("PersistQuest: Main() started.")

    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "PersistQuest", false, false)

    -- Start quest threads
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    local QuestCompleted_value = Quest:GetStateBool("QuestCompleted")
    QuestCompleted_value = Quest:PersistTransferBool(context, "QuestCompleted", QuestCompleted_value)
    Quest:SetStateBool("QuestCompleted", QuestCompleted_value)
    local Flag_value = Quest:GetStateBool("Flag")
    Flag_value = Quest:PersistTransferBool(context, "Flag", Flag_value)
    Quest:SetStateBool("Flag", Flag_value)
    local Count_value = Quest:GetStateInt("Count")
    Count_value = Quest:PersistTransferInt(context, "Count", Count_value)
    Quest:SetStateInt("Count", Count_value)
    local Ratio_value = Quest:GetStateString("Ratio")
    Ratio_value = Quest:PersistTransferString(context, "Ratio", Ratio_value)
    Quest:SetStateString("Ratio", Ratio_value)
    local Note_value = Quest:GetStateString("Note")
    Note_value = Quest:PersistTransferString(context, "Note", Note_value)
    Quest:SetStateString("Note", Note_value)
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("PersistQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("PersistQuest", true, false, false)
            Quest:DeactivateQuestLater("PersistQuest", 0)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

