-- PersistQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("PersistQuest: Init phase started.")
    Quest:AddQuestRegion("PersistQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("PersistQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "PersistQuest", false, false)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateBool("Flag", true)
    Quest:SetStateInt("Count", 2)
    Quest:SetStateFloat("Ratio", 1.25)
    Quest:SetStateString("Note", "Hi")
end

function Main(questObject)
    Quest = questObject
    Quest:Log("PersistQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Start quest threads
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferBool(context, "Flag")
    Quest:PersistTransferInt(context, "Count")
    Quest:PersistTransferFloat(context, "Ratio")
    Quest:PersistTransferString(context, "Note")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("PersistQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("PersistQuest", true, false, false)
            Quest:DeactivateQuestLater("PersistQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

