-- ExposedQuest.lua
-- Generated by Fable Quest Tool (FQT)

Quest = nil

-- Exposed variable helpers
local ExposedVarTypes = {
    ["ExposedEntity.IsReady"] = "Boolean",
    ["ExposedEntity.Count"] = "Integer",
    ["ExposedEntity.Ratio"] = "Float",
    ["ExposedEntity.Note"] = "String",
}

function GetExposedVar(name)
    local t = ExposedVarTypes[name] or "String"
    if t == "Boolean" then return Quest:GetStateBool(name) end
    if t == "Integer" then return Quest:GetStateInt(name) end
    if t == "Float" then return tonumber(Quest:GetStateString(name)) end
    return Quest:GetStateString(name)
end

function SetExposedVar(name, value)
    local t = ExposedVarTypes[name] or "String"
    if t == "Boolean" then Quest:SetStateBool(name, value) return end
    if t == "Integer" then Quest:SetStateInt(name, value) return end
    Quest:SetStateString(name, tostring(value))
end

function Init(questObject)
    Quest = questObject
    Quest:Log("ExposedQuest: Init phase started.")
    -- Initialize exposed variables
    Quest:SetStateBool("ExposedEntity.IsReady", true)
    Quest:SetStateInt("ExposedEntity.Count", 3)
    Quest:SetStateString("ExposedEntity.Ratio", tostring(1.5))
    Quest:SetStateString("ExposedEntity.Note", tostring("Hello"))

    Quest:AddQuestRegion("ExposedQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("ExposedQuest", 380, 340)
    Quest:SetStateBool("QuestCompleted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("ExposedQuest: Main() started.")

    -- Bind entity scripts
    Quest:AddEntityBinding("ExposedEntity", "ExposedQuest/Entities/ExposedEntity")
    Quest:FinalizeEntityBindings()

    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "ExposedQuest", false, false)

    -- Start quest threads
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    local QuestCompleted_value = Quest:GetStateBool("QuestCompleted")
    QuestCompleted_value = Quest:PersistTransferBool(context, "QuestCompleted", QuestCompleted_value)
    Quest:SetStateBool("QuestCompleted", QuestCompleted_value)
    -- Persist exposed variables
    local var_ExposedEntity_IsReady_value = Quest:GetStateBool("ExposedEntity.IsReady")
    var_ExposedEntity_IsReady_value = Quest:PersistTransferBool(context, "ExposedEntity.IsReady", var_ExposedEntity_IsReady_value)
    Quest:SetStateBool("ExposedEntity.IsReady", var_ExposedEntity_IsReady_value)
    local var_ExposedEntity_Count_value = Quest:GetStateInt("ExposedEntity.Count")
    var_ExposedEntity_Count_value = Quest:PersistTransferInt(context, "ExposedEntity.Count", var_ExposedEntity_Count_value)
    Quest:SetStateInt("ExposedEntity.Count", var_ExposedEntity_Count_value)
    local var_ExposedEntity_Ratio_value = Quest:GetStateString("ExposedEntity.Ratio")
    var_ExposedEntity_Ratio_value = Quest:PersistTransferString(context, "ExposedEntity.Ratio", var_ExposedEntity_Ratio_value)
    Quest:SetStateString("ExposedEntity.Ratio", var_ExposedEntity_Ratio_value)
    local var_ExposedEntity_Note_value = Quest:GetStateString("ExposedEntity.Note")
    var_ExposedEntity_Note_value = Quest:PersistTransferString(context, "ExposedEntity.Note", var_ExposedEntity_Note_value)
    Quest:SetStateString("ExposedEntity.Note", var_ExposedEntity_Note_value)
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("ExposedQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_ExposedEntity = Quest:GetThingWithScriptName("MK_OVID_DAD")
    if marker_ExposedEntity ~= nil then
        local pos_ExposedEntity = marker_ExposedEntity:GetPos()
        local ExposedEntity = Quest:CreateCreature("", pos_ExposedEntity, "ExposedEntity")
    else
        local hero = Quest:GetHero()
        local heroPos = hero:GetPos()
        local ExposedEntity = Quest:CreateCreature("", heroPos, "ExposedEntity")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    Quest:Log("ExposedQuest: EntitySpawner completed.")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("ExposedQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("ExposedQuest", true, false, false)
            Quest:DeactivateQuestLater("ExposedQuest", 0)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

