-- ContainerQuest.lua
-- Generated by Fable Quest Tool (FQT)

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("ContainerQuest: Init phase started.")
    Quest:AddQuestRegion("ContainerQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("ContainerQuest", 380, 340)
    Quest:SetStateBool("QuestCompleted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("ContainerQuest: Main() started.")

    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "ContainerQuest", false, false)

    -- Start quest threads
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    local QuestCompleted_value = Quest:GetStateBool("QuestCompleted")
    QuestCompleted_value = Quest:PersistTransferBool(context, "QuestCompleted", QuestCompleted_value)
    Quest:SetStateBool("QuestCompleted", QuestCompleted_value)
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("ContainerQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Container reward: Spawn and populate container
            Quest:Log("Attempting to spawn container...")
            local marker = Quest:GetThingWithScriptName("MK_REWARD")
            local containerPos
            if marker ~= nil then
                containerPos = marker:GetPos()
            else
                local hero = Quest:GetHero()
                containerPos = hero:GetPos()
            end
            Quest:Log("Creating container: OBJECT_CHEST at position...")
            local container = Quest:CreateObject("OBJECT_CHEST", containerPos, "RewardChest")
            Quest:Log("CreateObject returned: " .. tostring(container))
            if container ~= nil then
                Quest:Log("Container spawned successfully!")
                Quest:EntitySetTargetable(container, true)
                Quest:Log("Container set as targetable")
                Quest:GiveHeroObject("OBJECT_APPLE", 1)
                Quest:GiveHeroObject("OBJECT_CARROT", 1)
            else
                Quest:Log("WARNING: Failed to spawn container!")
            end

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("ContainerQuest", true, false, false)
            Quest:DeactivateQuestLater("ContainerQuest", 0)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end
