-- CardQuest.lua
-- Generated by Fable Quest Tool (FQT)

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("CardQuest: Init phase started.")
    Quest:AddQuestRegion("CardQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("CardQuest", 380, 340)
    Quest:SetStateBool("QuestCompleted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("CardQuest: Main() started.")

    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "CardQuest", false, false)
    Quest:SetQuestCardObjective("CardQuest", "Reach the gate", "Oakvale", "")

    Quest:SetQuestGoldReward("CardQuest", 50)
    Quest:SetQuestRenownReward("CardQuest", 25)

    -- Set quest info for start screen
    Quest:SetQuestInfoName("Card Quest")
    Quest:SetQuestInfoText("A story quest\\n\\nRewards: 50 Gold, 25 Renown, 1 item(s)")
    -- Show quest start screen
    Quest:KickOffQuestStartScreen("CardQuest", true, false)

    -- Start quest threads
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    local QuestCompleted_value = Quest:GetStateBool("QuestCompleted")
    QuestCompleted_value = Quest:PersistTransferBool(context, "QuestCompleted", QuestCompleted_value)
    Quest:SetStateBool("QuestCompleted", QuestCompleted_value)
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("CardQuest: Quest completed, giving rewards...")

            -- Give rewards
            Quest:GiveHeroGold(50)
            Quest:GiveHeroRenownPoints(25)
            Quest:GiveHeroObject("OBJECT_APPLE", 1)
            Quest:Pause(0)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("CardQuest", true, false, true)
            Quest:DeactivateQuestLater("CardQuest", 0)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

