-- ThreadQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("ThreadQuest: Init phase started.")
    Quest:AddQuestRegion("ThreadQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("ThreadQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "ThreadQuest", false, false)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("ThreadQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("SpawnedNpc", "ThreadQuest/Entities/SpawnedNpc")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
    Quest:CreateThread("WatcherThread", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("ThreadQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_SpawnedNpc = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_SpawnedNpc = nil
    if marker_SpawnedNpc ~= nil and marker_SpawnedNpc.GetPos ~= nil then
        local ok, result = pcall(function() return marker_SpawnedNpc:GetPos() end)
        if ok then
            pos_SpawnedNpc = result
        end
    end
    if pos_SpawnedNpc == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_SpawnedNpc = result
            end
        end
    end
    if pos_SpawnedNpc ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_VILLAGER_FARMER", pos_SpawnedNpc, "SpawnedNpc") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for SpawnedNpc")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    Quest:Log("ThreadQuest: EntitySpawner completed.")
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("ThreadQuest: Quest completed, giving rewards...")

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("ThreadQuest", true, false, false)
            Quest:DeactivateQuestLater("ThreadQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

function WatcherThread(questObject)
    Quest = questObject
    -- Watch for conditions
    -- TODO: Implement thread logic
end

