-- MyBoardQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyBoardQuest: Init phase started.")
    Quest:AddQuestRegion("MyBoardQuest", "Bowerstone")
    Quest:SetQuestWorldMapOffset("MyBoardQuest", 250, 250)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyBoardQuest", false, false)
    Quest:SetQuestCardObjective("MyBoardQuest", "Defeat the thief", "Bowerstone", "")
    Quest:SetQuestGoldReward("MyBoardQuest", 1200)
    Quest:SetQuestRenownReward("MyBoardQuest", 100)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateBool("Quest Accepted", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyBoardQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("QuestGiver", "MyBoardQuest/Entities/QuestGiver")
    Quest:AddEntityBinding("Thief", "MyBoardQuest/Entities/Thief")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Bowerstone"})
    Quest:CreateThread("EntitySpawner", {region="Bowerstone"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Bowerstone"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferBool(context, "Quest Accepted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Bowerstone - FSE auto-waits for region load
    Quest:Log("MyBoardQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_QuestGiver = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_QuestGiver = nil
    if marker_QuestGiver ~= nil and marker_QuestGiver.GetPos ~= nil then
        local ok, result = pcall(function() return marker_QuestGiver:GetPos() end)
        if ok then
            pos_QuestGiver = result
        end
    end
    if pos_QuestGiver == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_QuestGiver = result
            end
        end
    end
    if pos_QuestGiver ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_QuestGiver, "QuestGiver") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for QuestGiver")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_Thief = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_Thief = nil
    if marker_Thief ~= nil and marker_Thief.GetPos ~= nil then
        local ok, result = pcall(function() return marker_Thief:GetPos() end)
        if ok then
            pos_Thief = result
        end
    end
    if pos_Thief == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_Thief = result
            end
        end
    end
    if pos_Thief ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BANDIT", pos_Thief, "Thief") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for Thief")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local QuestGiver = Quest:GetThingWithScriptName("QuestGiver")
    if QuestGiver ~= nil then
        Quest:SetThingHasInformation(QuestGiver, true)
        Quest:MiniMapAddMarker(QuestGiver, "QuestGiver")
    end
    local Thief = Quest:GetThingWithScriptName("Thief")
    if Thief ~= nil then
        Quest:SetThingHasInformation(Thief, true)
        Quest:MiniMapAddMarker(Thief, "Thief")
    end

    Quest:Log("MyBoardQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyBoardQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyBoardQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyBoardQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local QuestGiver = Quest:GetThingWithScriptName("QuestGiver")
            if QuestGiver ~= nil and not QuestGiver:IsNull() then
                Quest:ClearThingHasInformation(QuestGiver)
                Quest:MiniMapRemoveMarker(QuestGiver)
            end
            local Thief = Quest:GetThingWithScriptName("Thief")
            if Thief ~= nil and not Thief:IsNull() then
                Quest:ClearThingHasInformation(Thief)
                Quest:MiniMapRemoveMarker(Thief)
            end

            -- Give rewards
            Quest:GiveHeroGold(1200)
            Quest:GiveHeroExperience(200)
            Quest:GiveHeroRenownPoints(100)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyBoardQuest", true, false, false)
            Quest:DeactivateQuestLater("MyBoardQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

