-- DeliveryKnothole.lua
-- Entity script for MyDeliveryQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("DeliveryKnothole: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("DeliveryKnothole: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            local hasItem = false
            if Quest:IsObjectInHeroPossession("OBJECT_APPLE") then
    hasItem = true
            elseif Quest:GetNumberOfItemsOfTypeInInventory("OBJECT_APPLE") > 0 then
    hasItem = true
            elseif Quest:IsPlayerCarryingItemOfType("OBJECT_APPLE") then
    hasItem = true
            end
            if hasItem then
                local ok = pcall(function() Quest:ConfiscateItemsOfTypeFromHero("OBJECT_APPLE") end)
                local stillHas = false
                if Quest:GetNumberOfItemsOfTypeInInventory("OBJECT_APPLE") > 0 then
                    stillHas = true
                elseif Quest:IsObjectInHeroPossession("OBJECT_APPLE") then
                    stillHas = true
                elseif Quest:IsPlayerCarryingItemOfType("OBJECT_APPLE") then
                    stillHas = true
                end
                if not ok or stillHas then
                    Quest:TakeObjectFromHero("OBJECT_APPLE")
                end
                Quest:SetStateBool("deliveredKnothole", true)
                Me:SpeakAndWait("Thanks for the delivery!")
            else
                Me:SpeakAndWait("I don't have my package yet.")
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
