-- VarBoolQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("VarBoolQuest: Init phase started.")
    Quest:AddQuestRegion("VarBoolQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("VarBoolQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "VarBoolQuest", false, false)
    Quest:SetQuestCardObjective("VarBoolQuest", "Talk to the boolean demo NPC", "Oakvale", "")

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("VarBoolQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("VarBoolNPC", "VarBoolQuest/Entities/VarBoolNPC")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("VarBoolQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_VarBoolNPC = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_VarBoolNPC = nil
    if marker_VarBoolNPC ~= nil and marker_VarBoolNPC.GetPos ~= nil then
        local ok, result = pcall(function() return marker_VarBoolNPC:GetPos() end)
        if ok then
            pos_VarBoolNPC = result
        end
    end
    if pos_VarBoolNPC == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_VarBoolNPC = result
            end
        end
    end
    if pos_VarBoolNPC ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_VarBoolNPC, "VarBoolNPC") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for VarBoolNPC")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local VarBoolNPC = Quest:GetThingWithScriptName("VarBoolNPC")
    if VarBoolNPC ~= nil then
        Quest:SetThingHasInformation(VarBoolNPC, true)
        Quest:MiniMapAddMarker(VarBoolNPC, "VarBoolNPC")
    end

    Quest:Log("VarBoolQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "VarBoolQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "VarBoolQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("VarBoolQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local VarBoolNPC = Quest:GetThingWithScriptName("VarBoolNPC")
            if VarBoolNPC ~= nil and not VarBoolNPC:IsNull() then
                Quest:ClearThingHasInformation(VarBoolNPC)
                Quest:MiniMapRemoveMarker(VarBoolNPC)
            end

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("VarBoolQuest", true, false, false)
            Quest:DeactivateQuestLater("VarBoolQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

