-- VarListener.lua
-- Entity script for VarExternalFlowQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("VarListener: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("VarListener: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            if Quest:GetStateBool("VarSource.HasToken") then
                Me:SpeakAndWait("Ah, the bear! The boy will be chuffed. The girl can make do with a stick and her imagination.")
                Quest:SetStateBool("QuestCompleted", true)
                break
            else
                Me:SpeakAndWait("No bear, no peace. Go give that bully a lesson and bring the bear to VarSource.")
            end
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
