-- VarSource.lua
-- Entity script for VarExternalFlowQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("VarSource: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("VarSource: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        if Me:IsTalkedToByHero() then
            local hasItem = false
            if Quest:IsObjectInHeroPossession("OBJECT_TEDDY_BEAR_UNGIVEABLE") then
    hasItem = true
            elseif Quest:GetNumberOfItemsOfTypeInInventory("OBJECT_TEDDY_BEAR_UNGIVEABLE") > 0 then
    hasItem = true
            elseif Quest:IsPlayerCarryingItemOfType("OBJECT_TEDDY_BEAR_UNGIVEABLE") then
    hasItem = true
            end
            if hasItem then
                local ok = pcall(function() Quest:ConfiscateItemsOfTypeFromHero("OBJECT_TEDDY_BEAR_UNGIVEABLE") end)
                local stillHas = false
                if Quest:GetNumberOfItemsOfTypeInInventory("OBJECT_TEDDY_BEAR_UNGIVEABLE") > 0 then
                    stillHas = true
                elseif Quest:IsObjectInHeroPossession("OBJECT_TEDDY_BEAR_UNGIVEABLE") then
                    stillHas = true
                elseif Quest:IsPlayerCarryingItemOfType("OBJECT_TEDDY_BEAR_UNGIVEABLE") then
                    stillHas = true
                end
                if not ok or stillHas then
                    Quest:TakeObjectFromHero("OBJECT_TEDDY_BEAR_UNGIVEABLE")
                end
                Quest:SetStateBool("VarSource.HasToken", true)
                    Me:SpeakAndWait("Lovely. The boy gets his bear, the bully gets a bruise, and you get the glory. Go tell the listener.")
                    local actionId = Quest:GetStateInt("FQT_ActionCounter")
                    if actionId == nil then actionId = 0 end
                    actionId = actionId + 1
                    Quest:SetStateInt("FQT_ActionCounter", actionId)
                    Quest:SetStateString("FQT_Action_" .. tostring(actionId), "Highlight|VarListener|VarListener")
                    local actionId = Quest:GetStateInt("FQT_ActionCounter")
                    if actionId == nil then actionId = 0 end
                    actionId = actionId + 1
                    Quest:SetStateInt("FQT_ActionCounter", actionId)
                    Quest:SetStateString("FQT_Action_" .. tostring(actionId), "ShowMarker|VarListener|Listener")
                    local actionId = Quest:GetStateInt("FQT_ActionCounter")
                    if actionId == nil then actionId = 0 end
                    actionId = actionId + 1
                    Quest:SetStateInt("FQT_ActionCounter", actionId)
                    Quest:SetStateString("FQT_Action_" .. tostring(actionId), "ClearHighlight|VarSource|VarSource")
                    local actionId = Quest:GetStateInt("FQT_ActionCounter")
                    if actionId == nil then actionId = 0 end
                    actionId = actionId + 1
                    Quest:SetStateInt("FQT_ActionCounter", actionId)
                    Quest:SetStateString("FQT_Action_" .. tostring(actionId), "HideMarker|VarSource|VarSource")
            else
                Me:SpeakAndWait("A bully's leaning on a boy to hand over his bear. Go sort the bully out and bring the bear here. The girl can manage without it for once.")
            end
        end
        local wasPresented = Me:MsgIsPresentedWithItem()
        local presentedItemName = g_PresentedItemName
        if wasPresented then
    Quest:Log("Presented item: " .. tostring(presentedItemName))
    g_PresentedItemName = nil
        end
        if wasPresented and presentedItemName == "OBJECT_TEDDY_BEAR_UNGIVEABLE" then
            local ok = pcall(function() Quest:ConfiscateItemsOfTypeFromHero("OBJECT_TEDDY_BEAR_UNGIVEABLE") end)
            local stillHas = false
            if Quest:GetNumberOfItemsOfTypeInInventory("OBJECT_TEDDY_BEAR_UNGIVEABLE") > 0 then
                stillHas = true
            elseif Quest:IsObjectInHeroPossession("OBJECT_TEDDY_BEAR_UNGIVEABLE") then
                stillHas = true
            elseif Quest:IsPlayerCarryingItemOfType("OBJECT_TEDDY_BEAR_UNGIVEABLE") then
                stillHas = true
            end
            if not ok or stillHas then
                Quest:TakeObjectFromHero("OBJECT_TEDDY_BEAR_UNGIVEABLE")
            end
            Quest:SetStateBool("VarSource.HasToken", true)
                Me:SpeakAndWait("Lovely. The boy gets his bear, the bully gets a bruise, and you get the glory. Go tell the listener.")
                local actionId = Quest:GetStateInt("FQT_ActionCounter")
                if actionId == nil then actionId = 0 end
                actionId = actionId + 1
                Quest:SetStateInt("FQT_ActionCounter", actionId)
                Quest:SetStateString("FQT_Action_" .. tostring(actionId), "Highlight|VarListener|VarListener")
                local actionId = Quest:GetStateInt("FQT_ActionCounter")
                if actionId == nil then actionId = 0 end
                actionId = actionId + 1
                Quest:SetStateInt("FQT_ActionCounter", actionId)
                Quest:SetStateString("FQT_Action_" .. tostring(actionId), "ShowMarker|VarListener|Listener")
                local actionId = Quest:GetStateInt("FQT_ActionCounter")
                if actionId == nil then actionId = 0 end
                actionId = actionId + 1
                Quest:SetStateInt("FQT_ActionCounter", actionId)
                Quest:SetStateString("FQT_Action_" .. tostring(actionId), "ClearHighlight|VarSource|VarSource")
                local actionId = Quest:GetStateInt("FQT_ActionCounter")
                if actionId == nil then actionId = 0 end
                actionId = actionId + 1
                Quest:SetStateInt("FQT_ActionCounter", actionId)
                Quest:SetStateString("FQT_Action_" .. tostring(actionId), "HideMarker|VarSource|VarSource")
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
