-- MyKillQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyKillQuest: Init phase started.")
    Quest:AddQuestRegion("MyKillQuest", "BarrowFields")
    Quest:SetQuestWorldMapOffset("MyKillQuest", 300, 320)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyKillQuest", false, false)
    Quest:SetQuestCardObjective("MyKillQuest", "Defeat the bandit leader", "BarrowFields", "")
    Quest:SetQuestGoldReward("MyKillQuest", 1000)
    Quest:SetQuestRenownReward("MyKillQuest", 100)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateBool("Target Killed", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyKillQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("TargetBandit", "MyKillQuest/Entities/TargetBandit")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="BarrowFields"})
    Quest:CreateThread("EntitySpawner", {region="BarrowFields"})
    Quest:CreateThread("MonitorQuestCompletion", {region="BarrowFields"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferBool(context, "Target Killed")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to BarrowFields - FSE auto-waits for region load
    Quest:Log("MyKillQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_TargetBandit = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_TargetBandit = nil
    if marker_TargetBandit ~= nil and marker_TargetBandit.GetPos ~= nil then
        local ok, result = pcall(function() return marker_TargetBandit:GetPos() end)
        if ok then
            pos_TargetBandit = result
        end
    end
    if pos_TargetBandit == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_TargetBandit = result
            end
        end
    end
    if pos_TargetBandit ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BANDIT", pos_TargetBandit, "TargetBandit") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for TargetBandit")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local TargetBandit = Quest:GetThingWithScriptName("TargetBandit")
    if TargetBandit ~= nil then
        Quest:SetThingHasInformation(TargetBandit, true)
        Quest:MiniMapAddMarker(TargetBandit, "TargetBandit")
    end

    Quest:Log("MyKillQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyKillQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyKillQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyKillQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local TargetBandit = Quest:GetThingWithScriptName("TargetBandit")
            if TargetBandit ~= nil and not TargetBandit:IsNull() then
                Quest:ClearThingHasInformation(TargetBandit)
                Quest:MiniMapRemoveMarker(TargetBandit)
            end

            -- Give rewards
            Quest:GiveHeroGold(1000)
            Quest:GiveHeroExperience(250)
            Quest:GiveHeroRenownPoints(100)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyKillQuest", true, false, false)
            Quest:DeactivateQuestLater("MyKillQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

