-- MyBossQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyBossQuest: Init phase started.")
    Quest:AddQuestRegion("MyBossQuest", "Arena")
    Quest:SetQuestWorldMapOffset("MyBossQuest", 380, 280)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyBossQuest", false, false)
    Quest:SetQuestCardObjective("MyBossQuest", "Defeat the Arena Champion", "Arena", "")
    Quest:SetQuestGoldReward("MyBossQuest", 5000)
    Quest:SetQuestRenownReward("MyBossQuest", 500)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateBool("Boss Defeated", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyBossQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("ArenaChampion", "MyBossQuest/Entities/ArenaChampion")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Arena"})
    Quest:CreateThread("EntitySpawner", {region="Arena"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Arena"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferBool(context, "Boss Defeated")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Arena - FSE auto-waits for region load
    Quest:Log("MyBossQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_ArenaChampion = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_ArenaChampion = nil
    if marker_ArenaChampion ~= nil and marker_ArenaChampion.GetPos ~= nil then
        local ok, result = pcall(function() return marker_ArenaChampion:GetPos() end)
        if ok then
            pos_ArenaChampion = result
        end
    end
    if pos_ArenaChampion == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_ArenaChampion = result
            end
        end
    end
    if pos_ArenaChampion ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BANDIT_CHIEF", pos_ArenaChampion, "ArenaChampion") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for ArenaChampion")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local ArenaChampion = Quest:GetThingWithScriptName("ArenaChampion")
    if ArenaChampion ~= nil then
        Quest:SetThingHasInformation(ArenaChampion, true)
        Quest:MiniMapAddMarker(ArenaChampion, "ArenaChampion")
    end

    Quest:Log("MyBossQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyBossQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyBossQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyBossQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local ArenaChampion = Quest:GetThingWithScriptName("ArenaChampion")
            if ArenaChampion ~= nil and not ArenaChampion:IsNull() then
                Quest:ClearThingHasInformation(ArenaChampion)
                Quest:MiniMapRemoveMarker(ArenaChampion)
            end

            -- Give rewards
            Quest:GiveHeroGold(5000)
            Quest:GiveHeroExperience(1000)
            Quest:GiveHeroRenownPoints(500)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyBossQuest", true, false, false)
            Quest:DeactivateQuestLater("MyBossQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

