-- VarFloatQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("VarFloatQuest: Init phase started.")
    Quest:AddQuestRegion("VarFloatQuest", "Oakvale")
    Quest:SetQuestWorldMapOffset("VarFloatQuest", 380, 340)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "VarFloatQuest", false, false)
    Quest:SetQuestCardObjective("VarFloatQuest", "Talk to the float demo NPC", "Oakvale", "")

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("VarFloatQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("VarFloatNPC", "VarFloatQuest/Entities/VarFloatNPC")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Oakvale"})
    Quest:CreateThread("EntitySpawner", {region="Oakvale"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Oakvale"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Oakvale - FSE auto-waits for region load
    Quest:Log("VarFloatQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_VarFloatNPC = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_VarFloatNPC = nil
    if marker_VarFloatNPC ~= nil and marker_VarFloatNPC.GetPos ~= nil then
        local ok, result = pcall(function() return marker_VarFloatNPC:GetPos() end)
        if ok then
            pos_VarFloatNPC = result
        end
    end
    if pos_VarFloatNPC == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_VarFloatNPC = result
            end
        end
    end
    if pos_VarFloatNPC ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_VarFloatNPC, "VarFloatNPC") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for VarFloatNPC")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local VarFloatNPC = Quest:GetThingWithScriptName("VarFloatNPC")
    if VarFloatNPC ~= nil then
        Quest:SetThingHasInformation(VarFloatNPC, true)
        Quest:MiniMapAddMarker(VarFloatNPC, "VarFloatNPC")
    end

    Quest:Log("VarFloatQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "VarFloatQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "VarFloatQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("VarFloatQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local VarFloatNPC = Quest:GetThingWithScriptName("VarFloatNPC")
            if VarFloatNPC ~= nil and not VarFloatNPC:IsNull() then
                Quest:ClearThingHasInformation(VarFloatNPC)
                Quest:MiniMapRemoveMarker(VarFloatNPC)
            end

            -- Give rewards

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("VarFloatQuest", true, false, false)
            Quest:DeactivateQuestLater("VarFloatQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

