-- Karen.lua
-- Entity script for NewQuest
-- Generated by FSE Quest Creator Pro
-- WORKING EXAMPLE - Demonstrates entity behavior patterns

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Me:MakeBehavioral()  -- Entity has AI behavior
    Me:AcquireControl()  -- Take control of entity
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        -- Talk trigger
        if Me:IsTalkedToByHero() then
            if Quest:IsPlayerCarryingItemOfType("OBJECT_TEDDY_BEAR") then
                -- Has teddy bear - complete quest
                Me:SpeakAndWait("Hey, give me that bear!")
                Quest:TakeObjectFromHero("OBJECT_TEDDY_BEAR")
                Me:SpeakAndWait("Stupid kid, how's the girl gonna get her teddy now? Well at least you get this useless sword I guess.")
                Quest:SetStateBool("QuestCompleted", true)
            else
                -- Doesn't have teddy bear - give quest
                Me:SpeakAndWait("Go find me a teddy bear, or else.")
                local answer = Quest:GiveHeroYesNoQuestion("Do you accept?", "Yes", "No", "I'm not sure")
                -- Could check answer here and react differently
            end
        end

        -- Kill trigger
        if Me:IsKilledByHero() then
            Quest:SetStateBool("QuestCompleted", true)
        end

        -- CRITICAL: Loop control - must be at end of while loop
        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    -- CRITICAL: Always release control at end
    Me:ReleaseControl()
end
