-- Merchant.lua
-- Entity script for MyFetchQuest
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

local Quest = nil
local Me = nil

function Init(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Merchant: Init called")
    Me:MakeBehavioral()
    Me:AcquireControl()
end

function Main(questObject, meObject)
    Quest = questObject
    Me = meObject
    Quest:Log("Merchant: Main started")
    local hero = Quest:GetHero()

    -- Main behavior loop
    while true do
        local wasPresented = Me:MsgIsPresentedWithItem()
        local presentedItemName = g_PresentedItemName
        if wasPresented then
    Quest:Log("Presented item: " .. tostring(presentedItemName))
    g_PresentedItemName = nil
        end
        if wasPresented and presentedItemName == "OBJECT_APPLE" then
            local ok = pcall(function() Quest:ConfiscateItemsOfTypeFromHero("OBJECT_APPLE") end)
            local stillHas = false
            if Quest:GetNumberOfItemsOfTypeInInventory("OBJECT_APPLE") > 0 then
                stillHas = true
            elseif Quest:IsObjectInHeroPossession("OBJECT_APPLE") then
                stillHas = true
            elseif Quest:IsPlayerCarryingItemOfType("OBJECT_APPLE") then
                stillHas = true
            end
            if not ok or stillHas then
                Quest:TakeObjectFromHero("OBJECT_APPLE")
            end
            Me:SpeakAndWait("Ah, just what I needed. Thank you!")
            Quest:SetStateBool("QuestCompleted", true)
            break
        end

        if Me:IsNull() then break end
        if not Quest:NewScriptFrame(Me) then break end
    end

    Me:ReleaseControl()
end
