-- MyInvestigationQuest.lua
-- Generated by FSE Quest Creator Pro
-- Generator: FQT-StartScreenFix-2026-02-10

Quest = nil

function Init(questObject)
    Quest = questObject
    Quest:Log("MyInvestigationQuest: Init phase started.")
    Quest:AddQuestRegion("MyInvestigationQuest", "Bowerstone")
    Quest:SetQuestWorldMapOffset("MyInvestigationQuest", 250, 250)
    -- Configure quest card
    Quest:AddQuestCard("OBJECT_QUEST_CARD_GENERIC", "MyInvestigationQuest", false, false)
    Quest:SetQuestCardObjective("MyInvestigationQuest", "Investigate the missing artifact", "Bowerstone", "")
    Quest:SetQuestGoldReward("MyInvestigationQuest", 1500)
    Quest:SetQuestRenownReward("MyInvestigationQuest", 150)

    Quest:SetStateBool("QuestCompleted", false)
    Quest:SetStateBool("FQT_StartScreenShown", false)
    Quest:SetStateBool("FQT_DebugStartScreen", false)
    Quest:SetStateBool("FQT_DebugStartScreenBanner", false)
    Quest:SetStateInt("Clues Found", 0)
    Quest:SetStateBool("Talked to Witness 1", false)
    Quest:SetStateBool("Talked to Witness 2", false)
end

function Main(questObject)
    Quest = questObject
    Quest:Log("MyInvestigationQuest: Main() started.")
    Quest:Log("FQT-StartScreenFix-2026-02-10: generator active")

    -- Bind entity scripts
    Quest:AddEntityBinding("Witness1", "MyInvestigationQuest/Entities/Witness1")
    Quest:AddEntityBinding("Witness2", "MyInvestigationQuest/Entities/Witness2")
    Quest:AddEntityBinding("Investigator", "MyInvestigationQuest/Entities/Investigator")
    Quest:FinalizeEntityBindings()

    -- Start quest threads
    Quest:CreateThread("FQT_StartScreen", {region="Bowerstone"})
    Quest:CreateThread("EntitySpawner", {region="Bowerstone"})
    Quest:CreateThread("MonitorQuestCompletion", {region="Bowerstone"})
end

function OnPersist(questObject, context)
    Quest = questObject
    Quest:PersistTransferBool(context, "QuestCompleted")
    Quest:PersistTransferInt(context, "Clues Found")
    Quest:PersistTransferBool(context, "Talked to Witness 1")
    Quest:PersistTransferBool(context, "Talked to Witness 2")
end

function EntitySpawner(questObject)
    Quest = questObject
    -- Thread is region-bound to Bowerstone - FSE auto-waits for region load
    Quest:Log("MyInvestigationQuest: EntitySpawner executing (region is loaded).")

    -- Brief pause to let game settle after region load
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end

    -- Spawn entities
    local marker_Witness1 = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_Witness1 = nil
    if marker_Witness1 ~= nil and marker_Witness1.GetPos ~= nil then
        local ok, result = pcall(function() return marker_Witness1:GetPos() end)
        if ok then
            pos_Witness1 = result
        end
    end
    if pos_Witness1 == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_Witness1 = result
            end
        end
    end
    if pos_Witness1 ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_Witness1, "Witness1") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for Witness1")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_Witness2 = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_Witness2 = nil
    if marker_Witness2 ~= nil and marker_Witness2.GetPos ~= nil then
        local ok, result = pcall(function() return marker_Witness2:GetPos() end)
        if ok then
            pos_Witness2 = result
        end
    end
    if pos_Witness2 == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_Witness2 = result
            end
        end
    end
    if pos_Witness2 ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_FEMALE_UNEMPLOYED", pos_Witness2, "Witness2") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for Witness2")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    local marker_Investigator = Quest:GetThingWithScriptName("MK_OVID_DAD")
    local pos_Investigator = nil
    if marker_Investigator ~= nil and marker_Investigator.GetPos ~= nil then
        local ok, result = pcall(function() return marker_Investigator:GetPos() end)
        if ok then
            pos_Investigator = result
        end
    end
    if pos_Investigator == nil then
        local hero = Quest:GetHero()
        if hero ~= nil and hero.GetPos ~= nil then
            local ok, result = pcall(function() return hero:GetPos() end)
            if ok then
                pos_Investigator = result
            end
        end
    end
    if pos_Investigator ~= nil then
        pcall(function() Quest:CreateCreature("CREATURE_BOWERSTONE_POSH_VILLAGER_MALE_UNEMPLOYED", pos_Investigator, "Investigator") end)
    else
        Quest:Log("FQT: Failed to resolve spawn position for Investigator")
    end

    -- Brief pause to allow entity to fully spawn
    Quest:Pause(0.1)
    if not Quest:NewScriptFrame() then return end

    -- Set up quest target highlighting and minimap markers
    local Witness1 = Quest:GetThingWithScriptName("Witness1")
    if Witness1 ~= nil then
        Quest:SetThingHasInformation(Witness1, true)
        Quest:MiniMapAddMarker(Witness1, "Witness1")
    end
    local Witness2 = Quest:GetThingWithScriptName("Witness2")
    if Witness2 ~= nil then
        Quest:SetThingHasInformation(Witness2, true)
        Quest:MiniMapAddMarker(Witness2, "Witness2")
    end
    local Investigator = Quest:GetThingWithScriptName("Investigator")
    if Investigator ~= nil then
        Quest:SetThingHasInformation(Investigator, true)
        Quest:MiniMapAddMarker(Investigator, "Investigator")
    end

    Quest:Log("MyInvestigationQuest: EntitySpawner completed.")
end

function FQT_StartScreen(questObject)
    Quest = questObject
    local debugStart = Quest:GetStateBool("FQT_DebugStartScreen")
    local alreadyShown = Quest:GetStateBool("FQT_StartScreenShown")
    if alreadyShown == nil then alreadyShown = false end
    if alreadyShown then
        if debugStart then Quest:Log("FQT: start screen already shown") end
        return
    end
    Quest:Pause(0.5)
    if not Quest:NewScriptFrame() then return end
    local questName = "MyInvestigationQuest"
    local activeQuest = Quest:GetActiveQuestName()
    if debugStart then Quest:Log("FQT: active quest before start = " .. tostring(activeQuest)) end
    if activeQuest == nil or activeQuest == "" or activeQuest ~= questName then
        Quest:ActivateQuest(questName)
        Quest:Pause(0.1)
        if not Quest:NewScriptFrame() then return end
        activeQuest = Quest:GetActiveQuestName()
        if debugStart then Quest:Log("FQT: active quest after activate = " .. tostring(activeQuest)) end
    end
    Quest:SetHeroGuideShowsQuestCards(true)
    Quest:GiveQuestCardDirectly("OBJECT_QUEST_CARD_GENERIC", "MyInvestigationQuest", true)
    if debugStart then Quest:Log("FQT: gave quest card directly") end
    Quest:Log("FQT: KickOffQuestStartScreen called")
    Quest:KickOffQuestStartScreen(questName, true, true)
    if Quest:GetStateBool("FQT_DebugStartScreenBanner") then
        Quest:AddScreenTitleMessage("FQT: Start screen invoked", 3.0, true)
    end
    Quest:SetStateBool("FQT_StartScreenShown", true)
    if debugStart then Quest:Log("FQT: start screen kicked off") end
end

function MonitorQuestCompletion(questObject)
    Quest = questObject
    while true do
        if Quest:GetStateBool("QuestCompleted") then
            Quest:Log("MyInvestigationQuest: Quest completed, giving rewards...")

            -- Clear quest target highlighting and minimap markers
            local Witness1 = Quest:GetThingWithScriptName("Witness1")
            if Witness1 ~= nil and not Witness1:IsNull() then
                Quest:ClearThingHasInformation(Witness1)
                Quest:MiniMapRemoveMarker(Witness1)
            end
            local Witness2 = Quest:GetThingWithScriptName("Witness2")
            if Witness2 ~= nil and not Witness2:IsNull() then
                Quest:ClearThingHasInformation(Witness2)
                Quest:MiniMapRemoveMarker(Witness2)
            end
            local Investigator = Quest:GetThingWithScriptName("Investigator")
            if Investigator ~= nil and not Investigator:IsNull() then
                Quest:ClearThingHasInformation(Investigator)
                Quest:MiniMapRemoveMarker(Investigator)
            end

            -- Give rewards
            Quest:GiveHeroGold(1500)
            Quest:GiveHeroExperience(350)
            Quest:GiveHeroRenownPoints(150)

            -- Complete and deactivate quest
            Quest:SetQuestAsCompleted("MyInvestigationQuest", true, false, false)
            Quest:DeactivateQuestLater("MyInvestigationQuest", 10)
            break
        end
        Quest:Pause(0.5)
        if not Quest:NewScriptFrame() then break end
    end
end

